### PR TITLE
Microsoft.Data.Sqlite: Differentiate between "Foreign Keys=False" and the default

### PR DESCRIPTION
**Pull request by bricelam**
:trollface: 
🦶💥🔫

### CODE REVIEW

**Comment by bricelam** [comment]
I realized this is actually valuable as a mitigation to removing `SqliteDbContextOptionsBuilder.SuppressForeignKeyEnforcement()`. Despite my memory of its design, it actually sent `PRAGMA foreign_keys = 0` too.

**Comment by roji** [comment]
Proposed additional emoji: :clock1: :clock4: :clock7: :clock12:

**Comment by ajcvickers** [comment]
One Four Seven Twelve? 14712?

**Comment by bricelam** [comment]
I think he was going for a ticking time bomb

**Comment by roji** [comment]
More like a representation on the time spent discussing :)

**Comment by ajcvickers** [comment]
We just wanted to give you a taste of how API review meetings go. ;-)

**Pull request merged**
