### PR TITLE
Add CODEOWNERS starting point

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
Anyone else want in on this?

**Comment by ajcvickers** [comment]
EF Team: @AndriySvyryd @bricelam @divega @roji @lajones @maumar @smitpatel Is this something we want? (To me it seems like extra metadata to maintain with little real benefit.)

**Comment by AndriySvyryd** [comment]
Not needed, too few owners

**Comment by dougbu** [comment]
> To me it seems like extra metadata to maintain with little real benefit.

I appreciate knowing what's changing in the `eng/` folder across all of our repos. Do you object to me creating the file as-is?

**Comment by roji** [comment]
Not sure we'd really benefit, but it could maybe help bring PRs to each area's owner a bit more quickly...

That said no apparent harm in having it for `eng` either I think...

**Comment by bricelam** [comment]
@dougbu Would this also require you to sign off on the PRs or have we disabled that aspect of ownership?

**Comment by dougbu** [comment]
@bricelam no sign-off needed. I'll get _invited_ as a review but that's it.

**Pull request merged**
