### PR TITLE
Add ToLookupAsync extension methods for IQueryable

### PR DESCRIPTION
**Pull request by huysentruitw**
Needed this in a lot of cases already. The latest need was to fetch data for a GraphQL [CollectionBatchDataLoader](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/DataLoader/CollectionBatchDataLoader.cs).

### CODE REVIEW

**Comment by huysentruitw** [comment]
I've searched for ToDictionaryAsync tests, but didn't find any. You can tag me in that issue for adding tests of these extension methods.

**Comment by ajcvickers** [comment]
Changing base to master to merge for 3.0.

**Comment by divega** [comment]
@maumar can you please write down what you found with the investigation you did about this? Do we need new issues to track missing test coverage.

**Comment by divega** [comment]
@huysentruitw Thanks a lot for submitting this PR. At this point we are locking down 2.2, so we will consider it for 3.0.

**Comment by pbarranis** [comment]
It seems like these extension methods were removed from EntityFrameworkQueryableExtensions.cs sometime between when they were merged to master and when the file was moved from src/EFCore/ to src/EFCore/Extensions.  Was this intentional?

I'm afraid I don't know how to get at the history of EntityFrameworkQueryableExtensions.cs on GitHub before it was moved.  From what I'm reading online it's not possible; you have to have the repo locally and use git commands to investigate further.

**Comment by smitpatel** [comment]
@pbarranis - We removed it intentionally. It was removed in 3.0 release. And we decided not to add it again as per #15916. Removed in #15983

In order to use Take EF Core queryable and enumerate it using AsEnumerable/AsAsyncEnumerable. Then you can use ToLookup API from other libraries (sync from corefx, async from IX-Async).

**Comment by huysentruitw** [comment]
I took the same approach as ToDictionary. Why remove one but not the other? You can as well remove ToList, ToArray and ToDictionary as well then, right?

**Comment by smitpatel** [comment]
@huysentruitw - Your approach was same when EF Core used IX-Async underneath. EF Core 3.x onwards it does not. For ToList/ToArray/ToDictionary, it is easy to implement it from corefx library. ToLookup requires access to Lookup which is defined internal in corefx. As noted explicitly in the issue I linked, we decided not to define that ourselves. If `Dictionary<,>` was internal too, we would remove that too.

**Pull request merged**
