### PR TITLE
Merge release/3.1 to master 2

### PR DESCRIPTION
**Pull request by smitpatel**

### CODE REVIEW

**Comment by smitpatel** [comment]
@dougbu - Are any of these changes suppose to go in master or it should do no-op merge to master? If anything is required in master then please add appropriate commit to this PR.

**Comment by dougbu** [comment]
@smitpatel what is the target branch intended for? If it's somewhat like 'master', then the Arcade changes and the changes @JunTaoLuo made to use `$(DefaultNetCoreTargetFramework)` should come through. Any place you see 'netcoreapp3.1' should instead or in addition read 'netcoreapp5.0'.

The lack of change in global.json is a problem and the eng/Version*.* files bring through 3.1 changes and that doesn't seem correct. Should _at least_ update dependencies from dotnet/arcade.

**Comment by smitpatel** [comment]
@dougbu - Target branch will go to master, just unwinding bot & dev changes. Dev changes will just to go master as is. Bot changes, I don't know what changes should be carried forward and what should be ignored hence the PR so that you can guide in that direction.

For this PR, if I understand your message then 
- Change all netcoreapp3.1 to netcoreapp5.0 while merging?
- All version changes except for arcade SDK version should be ignored.

Let me know if any missed.

**Comment by dougbu** [comment]
2 things:
- merging individual commits in separate batches is likely to _really_ mess up the history in 'master'
- the bot already has a PR open to do the merge and @JunTaoLuo is doing what you said: flowing dev updates and adjusting the infrastructure changes to merge properly

> Change all netcoreapp3.1 to netcoreapp5.0 while merging?

Not exactly. This repo contains some projects that list almost-every TFM ever. Those projects should have **both** 'netcoreapp3.1' and 'netcoreapp5.0' in their `$(TargetFrameworks)`.

**Pull request closed without merging**
