### PR TITLE
Update to latest, coherent dependencies

### PR DESCRIPTION
**Pull request by natemcmaster**
Generated using this script https://github.com/aspnet/AspNetCore-Internal/pull/1830

### CODE REVIEW

**Comment by natemcmaster** [comment]
EF.Design tests fail on .NET Frameowrk with
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.GetSequencePoints(MethodDebugInformationHandle handle)
   at System.Diagnostics.StackTraceSymbols.GetSourceLineInfoWithoutCasAssert(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize, Int32 methodToken, Int32 ilOffset, String& sourceFile, Int32& sourceLine, Int32& sourceColumn)
   at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32 iSkip, Boolean fNeedFileInfo, Exception exception)
   at System.Diagnostics.StackTrace.CaptureStackTrace(Int32 iSkip, Boolean fNeedFileInfo, Thread targetThread, Exception e)
   at System.Diagnostics.StackTrace..ctor(Exception e, Boolean fNeedFileInfo)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactoryTest.Create_works_when_BuildWebHost_throws()
```

**Comment by dougbu** [comment]
> EF.Design tests fail on .NET Framework with&hellip;

Huh? All checks have passed

**Comment by natemcmaster** [comment]
They passed on retry. Must be a flaky test.

**Comment by bricelam** [comment]
@natemcmaster Any update from Arcade on when they plan to address these issues?

**Comment by dougbu** [comment]
@bricelam hopefully this week

**Pull request merged**
