### PR TITLE
Replace Newtonsoft.Json with System.Text.Json.

### PR DESCRIPTION
**Pull request by qbikez**
Remove Newtonsoft.Json dependency from dotnet-ef and replaces it with System.Text.JSon. (#14571)

### CODE REVIEW

**Comment by bricelam** [comment]
@ajcvickers We still use JSON.NET in our tests ([here](https://github.com/aspnet/EntityFrameworkCore/blob/dc51ab4aeef003175e64c41fe187ed5c0f153010/test/EFCore.Tests/ModelBuilding/TestModel.cs#L468-L473) and [here](https://github.com/aspnet/EntityFrameworkCore/blob/dc51ab4aeef003175e64c41fe187ed5c0f153010/test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs#L807-L820)). Do we want to do anything about it?

**Comment by smitpatel** [comment]
@bricelam - If that is the only place and if we want to remove it, you can easily replace `Jobject` with any type which implements IEnumerable.

**Comment by bricelam** [comment]
Yeah, that the only remaining place outside of Cosmos.

**Comment by bricelam** [comment]
Looks like `JsonObject` still fits the bill.

**Comment by bricelam** [comment]
I'll remove it.

**Comment by ajcvickers** [comment]
Just to complete the loop here I think using it in our tests is fine. Also, Cosmos using it has been confirmed as fine for now.

**Pull request merged**
