### PR TITLE
Changing Migration2 to RenameColumn.

### PR DESCRIPTION
**Pull request by cincuranet**

### CODE REVIEW

**Comment by cincuranet** [comment]
PR for discussion in #14749.

**Comment by cincuranet** [comment]
@ajcvickers Some checks are failing, but seems to be because the whole master is failing. Would you like me to rebase on top of specific tag/commit/branch?

**Comment by bricelam** [comment]
(Rebased on master. This triggers another CI run.)

**Comment by ajcvickers** [comment]
Thanks!

**Pull request merged**
