### PR TITLE
Update dotnet-ef to netcoreapp2.1

### PR DESCRIPTION
**Pull request by bricelam**
Arbitrary constraints must be satisfied.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@ryanbrandenburg Why is this failing in dev, but not 2.1 release?

**Comment by ryanbrandenburg** [comment]
Because dev took a new SDK.

**Comment by natemcmaster** [comment]
It's probably best -- for the sake of consistency -- that dotnet-ef target netcoreapp2.1, but I don't know if this is essential to shipping 2.1. It all depends on how the CLI builds.

@wli3 - when you consume dotnet-ef to produce the BundledTools folder in the CLI, does it matter which TFM the tools package target?

**Comment by ajcvickers** [comment]
@natemcmaster Agree that we should take this for RTM. Do we think there is any chance RC is broken without this fix?

**Comment by natemcmaster** [comment]
Discussed in person. Whether it works in RC or not depends on how well rollforward from .NET Core 2.0 to 2.1 works. There are known issues in that feature at the moment, but I'm not sure if they will affect dotnet-ef.

**Comment by wli3** [comment]
Technically it doesn't matter now. But I do think it should be automatically inline with the TFM and runtime shipped with SDK (or just the latest) . Say if there is breaking runtime version in the future we don't have to manually update it.

**Pull request merged**
