### PR TITLE
Ordering fix (#19220)

### LINKED ISSUE #19220: Where_subquery_anon_nested is missing explicit order
The `Where_subquery_anon_nested` test is missing explicit order in the 3rd subquery and hence can sometimes fail.

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #19220.

### CODE REVIEW

**Comment by cincuranet** [comment]
Looks like the checks are lost now. Will reopen new PR.

**Comment by cincuranet** [comment]
Didn't help at all. Can somebody re-trigger this or maybe #19225...

@roji, @ajcvickers

**Comment by smitpatel** [comment]
The PR is in draft mode so checks won't run. Once you hit ready for review and make it normal PR it will trigger automatically.

**Comment by cincuranet** [comment]
Not really. It already did run [here](https://dev.azure.com/dnceng/public/_build/results?buildId=450454) (and [here](https://dev.azure.com/dnceng/public/_build/results?buildId=450431)), but the Azure DevOps somewhat failed and now GitHub is confused.

But I marked it as ready for review anyway.

**Comment by cincuranet** [comment]
Voila. :shipit:

**Comment by ajcvickers** [comment]
Thanks!

(Note: ran Cosmos tests locally before merging.)

**Pull request merged**
