### PR TITLE
Add commented-pubternal attributes

### PR DESCRIPTION
**Pull request by ajcvickers**

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
Why?

**Comment by ajcvickers** [comment]
@AndriySvyryd See https://github.com/aspnet/EntityFrameworkCore/pull/15087

**Comment by ajcvickers** [comment]
@AndriySvyryd No need to review.

**Comment by AndriySvyryd** [comment]
Add `WIP`?

**Comment by ajcvickers** [comment]
@AndriySvyryd Well, I'm not planning to do any more to it, so it's not really in-progress. And it could me merged as-if, if that's what makes sense to @roji. So I guess I will assign to him. :-)

**Comment by roji** [comment]
Confirmed, I'll be merging this PR into #15087.

**Pull request closed without merging**
