### PR TITLE
Update to Oracle Data Access package naming

### PR DESCRIPTION
**Pull request by smitpatel**

### CODE REVIEW

**Comment by smitpatel** [comment]
We don't need old naming. These names are for automation script only.

**Comment by ralmsdeveloper** [comment]
I did not do this by believing it could affect something in the Universe.

**Comment by smitpatel** [comment]
Dependency updates are required to be done in Universe and then rolled into individual repo. Overall the process is not smooth or easy anyway.

**Comment by ralmsdeveloper** [comment]
Thanks @smitpatel, Good to know.

**Pull request merged**
