### PR TITLE
Merge release/3.1 to master

### PR DESCRIPTION
**Pull request by smitpatel**

### CODE REVIEW

**Comment by dougbu** [comment]
How is this better than / different from adjusting what's in the #17779 branch?

**Comment by smitpatel** [comment]
Can you update #17779 branch without any input from anyone from EF team? If yes, then sounds good to me. If answer is no then sorry I don't see why we have to take that overhead. We have been pretty consistent in merging release/3.1 to master with dev commits. The issues happen when auto-generated PR is not taken care properly in time and it entangle all the developer flow for us. This discussion has been repeated over and over again with @ajcvickers .

I created separate branches so you guys can tell what should flow and what should not. If not, I can just discard all the changes from release/3.1 which are not product changes and you guys can update master branch yourself later. Either works for me.

It hurts my eyes to see mess created by automated merges. 😢

**Comment by dougbu** [comment]
Can't disagree about some of the bot's merges. Not sure the strudel you laid out here is much better but to each his own.

In any case, I don't know anything about the `ModelSourceTests` changes and the Version*.* changes should not come into master.

What's missing is the stabilize version changes. That should be merged but with `$(StabilizePackageVersion)` set to `false`. Will need to cherry-pick that now I guess.

**Comment by dougbu** [comment]
Oops, that block is missing in 'release/3.1' too ☹️

**Pull request closed without merging**
