### PR TITLE
Cursor-based paging WIP.

### PR DESCRIPTION
**Pull request by benmccallum**
This is just a WIP on a solution to #14104.
Just a draft for now so we can discuss the changes I'm making informally with a nice diff.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@divega to follow up.

**Comment by benmccallum** [comment]
I'd love some advice on whether the approach I'm taking is actually the correct one; see the issue for my latest comment on what I've done so far. Thanks team!

**Comment by smitpatel** [comment]
@benmccallum - Looking at PR, I would suggest holding off for now. I see that you have added new Queryable operator for Take(Before/After)Match and plumbed it through Relinq parser though there is no translation further. In 3.0, we are going away from Relinq QueryModel hence some of it would be unnecessary and translation would be directly from expression tree. The new pipeline without QM is being worked in #14455. In few weeks it should be ready to be merged and then we can add new features to query.

**Comment by benmccallum** [comment]
Awesome, thx for the heads up @smitpatel. Will hold off a bit longer!

**Comment by benmccallum** [comment]
Closing as per above.

**Pull request closed without merging**
