### PR TITLE
Optimize translation of string.{Starts,Ends}With

### LINKED ISSUE #14657: string.StartsWith translator LEFT(LEN()) problem
Hello everyone,

As it's written in [SqlServerStartsWithOptimizedTranslator.cs](/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStartsWithOptimizedTranslator.cs) `string.StartsWith` is translated as two expression, `Like` and `LEFT(LEN())`. As I have found, a reason of making `LEFT(LEN())` is optimization.
I took executed script from my application and try to run first as it was executed and then without second part of expression. It seems that in my case, `LEFT(LEN())` is slowing the execution.

Is it possible to skip `LEFT(LEN())` expression in any way?

### PR DESCRIPTION
**Pull request by roji**
* If the pattern is constant, we now escape it client-side and send a
  simple LIKE expression - no need for LEFT(LEN())
* Merged the StartsWith and EndsWith translators for each provider

Fixes #14657

### CODE REVIEW

**Comment by ErikEJ** [comment]
Providers fyi?

**Comment by roji** [comment]
Sure thing. Note that this is a purely provider-internal implementation detail, so no need for other providers to do anything unless they want to copy the same optimization.

**Comment by ErikEJ** [comment]
>> unless they want to copy the same optimization.

Thanks!

**Comment by smitpatel** [comment]
@roji - Would you like to submit this fix to new query pipeline?

**Comment by roji** [comment]
@smitpatel oh so there's no point in this PR as it is, against current master? Is your branch already in a state where it can receive this (and pass tests)?

**Comment by smitpatel** [comment]
Precisely, I already deleted that file in new pipeline. My branch can receive changes and pass certain translation tests but the whole branch does not pass fully yet. It has hard dependency on new nav-rewrite.

**Comment by roji** [comment]
OK, no problem, will resubmit this against your branch then.

**Comment by roji** [comment]
It will be a good opportunity to start seeing what's going on in there :)

**Pull request closed without merging**
