### PR TITLE
Reformat test code

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Now with less build breaks!

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
@bricelam Pipelines is not picking up the updated code when I rerun the check

**Comment by smitpatel** [comment]
I triggered manually for now. I would expect re-run in GitHub UI would run the last commit again.
If you add commit (rather than force-push) then new commits will trigger builds. (Something I know for sure)

**Comment by AndriySvyryd** [comment]
@ajcvickers But I fixed them...

**Comment by AndriySvyryd** [comment]
Will checkin by EOD if no reviews are posted

**Pull request merged**
