### PR TITLE
Depend on latest version of Microsoft.NETCore.App

### LINKED ISSUE #14501: Not flowing dependency updates for Microsoft.NETCore.App
This repo is only flowing dependency updates for packages, but not for the actually .NET Core runtime (Microsoft.NETCore.App). That means bot-generated PRs such as https://github.com/aspnet/EntityFrameworkCore/pull/14500 are not actually testing EFCore with the latest .NET Core.

The repo is currently using the runtime version that is baked into the .NET Core SDK. The SDK version is not automatically updated by Arcade, and even if it were, it would often be at least 1 step behind the latest runtime version which will be inserted into the SDK.

@bricelam @ajcvickers - was this an intentional change when converting this repo to Arcade?

### PR DESCRIPTION
**Pull request by bricelam**
Resolves #14501

### CODE REVIEW

**Comment by natemcmaster** [comment]
I'm guessing all the test failures are a result of actually having NETcore.App 3.0.0-preview-27331-3 installed. Because Arcade doesn't support this yet (https://github.com/dotnet/arcade/issues/1441), you'll have to add code to this repo to do it yourself. See here for example:

https://github.com/aspnet/Extensions/blob/master/eng/Tools.props
https://github.com/aspnet/Extensions/blob/92acd8b95901f1e8f47d3d128cb5f7c38b684644/eng/Versions.props#L41

**Comment by bricelam** [comment]
Hmm... 12 failures all related to floating-point precision differences.

**Comment by natemcmaster** [comment]
> 12 failures all related to floating-point precision differences.

Yeah, we noticed the same kinds of failures in aspnet yesterday. I'm told these are intentional breaking changes, so we updated our tests.

cc @tannergooding @danmosemsft

**Comment by bricelam** [comment]
Thanks, I did see something recently about conforming to the latest IEEE standard... Will assume they're expected.

@ajcvickers This will break equality for values saved with the string converters in 2.x

**Comment by smitpatel** [comment]
https://blogs.msdn.microsoft.com/dotnet/2019/01/29/announcing-net-core-3-preview-2/#user-content-ieee-floating-point-improvements

**Comment by tannergooding** [comment]
Yes, `float.ToString()` and `double.ToString()` had a few breaking changes made to them.

`ToString()`, `ToString("G")`, and `ToString("R")` will now return the shortest roundtrippable string; ensuring that users end up with something that "just works" by default.
* This fixes the case where things like `double.Parse(Math.PI.ToString())` would not return `Math.PI` but instead a value that was off by ~9-17 ULP (units in last place)

The "G" format specifier that takes a precision (such as `"G17"`) should continue returning the same value as before; except for precisions above 15 where it will now return the requested number of significant digits (when those digits are available).
* This fixes the case where a user said `"G15"` or `"G16"` and we returned 17 digits
* This also fixes the case where a user said `"G20"` or `"G99"` and we only returned 17 digits

The "C", "E", "F", "N", and "P" format specifiers were modified such that precisions above 15 will now return the requested number of digits after the decimal point (when those digits are available). These formats will also now, when there are more than 15 significant digits available, ensure that those digits are properly initialized (rather than being set to zero).
* This fixes cases where the user specified something like `((double)(ulong.MaxValue)).ToString("F17")` and we returned `"18446744073709600000.00000000000000000""` when we should have returned `"18446744073709551615.00000000000000000"` (filling out the available integral digits)
* This fixes cases for `E` where the trailing digit was always zero (rather than set to the appropriate digit). For example `((double)(ulong.MaxValue)).ToSTring("E17")` was returning `"1.84467440737095520E+019"` when it should have returned `"1.84467440737095516E+019"`
* This fixes cases for `P` where the last two trailing digits were always zero (rather than set to the appropriate digit) (similar examples to the above)

**Comment by ajcvickers** [comment]
@bricelam We should keep the break in-mind when investigating any reported regressions, but it seems like moving forward with the new conversions is the way to go. Do you think we need to do more proactively here? /cc @divega 

@tannergooding Thanks for the detailed info!

**Comment by tannergooding** [comment]
As a note, if you are currently using `ToString()` or `ToString("G")` and you feel the above is "too breaking", you can provide the previous behavior via explicitly using `ToString("G15")`.

The downside would be as described above. That is, floating-point values serialized this way may not roundtrip to their original value. Numbers like `Math.PI` and `Math.E` are prime examples of this issue.

**Pull request merged**
