### PR TITLE
SQL Server scaffolding fixes

### LINKED ISSUE #5553: Reverse Engineer: Scaffolding fails on Azure Sql Server v11 and SQL 2008 because sequences are not supported
Steps to reproduce
`Scaffold-DbContext -Provider "Microsoft.EntityFrameworkCore.SqlServer" -Context "DbMercurySchool" -OutputDir "DataModel"  -Connection "Server=[Sql Azure Database Server];Data Source=[Sql Azure Database];Initial Catalog=MercurySchool;Persist Security Info=False;User ID=[User ID ];Password=[My Password];Pooling=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"`

The issue: SQL error thrown

`Error Number:208,State:1,Class:16 One or more errors occurred. (Invalid object name 'sys.sequences'.)`

See attached file.

[scaffold_error.txt](https://github.com/aspnet/EntityFramework/files/286958/scaffold_error.txt)

EF Core 
- version: `1.0.0-rc2-final`
- Operating system: Win 10
- Visual Studio version: VS 2015 Community

Other details about my project setup:

So far database has one table. The schema for the table is `academy` not `dbo`.

### LINKED ISSUE #14566: Hidden columns are scaffolded for Azure databases
Same problem as #8192, but for Azure SQL Databases. When scaffolding an Azure SQL Databases to EF Core, Hidden Columns are not excluded. As a result, columns used for SQL Temporal Tables get scaffolded back into the application.

From what I can see in the current implementation, the Temporal Tables feature detection is based on the server version (13 / SQL Server 2016).  This is a problem for Azure databases, which run on an engine based on SQL Server 2014, but have can have an higher compatibility level (i.e. SQL Server 2017).

### Steps to reproduce
Add Temporal System Versioning on an Azure database, then run Scaffold-DbContext from that database.

### PR DESCRIPTION
**Pull request by ErikEJ**
Use compatibility_level for feature detection
Unblock scaffolding on Azure SQL DW 

Maybe it is better to prevent scaffolding with SQL DW? 

https://docs.microsoft.com/en-us/azure/sql-data-warehouse/sql-data-warehouse-tables-overview#unsupported-table-features 

fixes #14566
fixes #5553

### CODE REVIEW

**Comment by ErikEJ** [comment]
@bricelam I have just done some integration testing of the SQL schema queries on Azure SQL DW and have two observations: 

1: The columns query fails with: 

    'OBJECT_DEFINITION' is not a recognized built-in function name.

2: The indexes query returns no primary keys (this concept does not exist is SQL DW), so not tables will be scaffolded! 

Would it be better to block completely on scaffolding a SQL DW database?

**Comment by bricelam** [comment]
Looks like OBJECT_DEFINITION is only used for column default SQL. Is there an alternative way to get that? If not, can we know that it has a default constraint and emit `.HasDefaultValueSql("")` possibly with a warning?

No primary keys seems fine. After #1679 and #5719 they'll just reverse engineer into entities without keys. The user can then update the model to specify the primary keys. If all they do is query, they don't really need keys anyway

**Comment by ErikEJ** [comment]
Ok, then we should unblock!!

I think default constraints simply do not exist with SQL DW, so we could do a conditional for that engineedition?

**Comment by ErikEJ** [comment]
Ah, it supports default constraints: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-azure-sql-data-warehouse?view=aps-pdw-2016-au7 - I will look for an alternative way of getting them then.

**Pull request merged**
