### PR TITLE
Add missing semicolons in scaffolding test SQL

### PR DESCRIPTION
**Pull request by roji**
@bricelam, found this while copy-pasting tests, not sure if SQL Server is actually parsing this without the semicolons?

### CODE REVIEW

**Comment by bricelam** [comment]
Transact-SQL doesn't usually need them

**Comment by smitpatel** [comment]
Hey @bricelam 
```

[xUnit.net 00:03:40.9443525]     Microsoft.EntityFrameworkCore.PropertyEntrySqliteTest.Property_entry_original_value_is_set [FAIL]

[xUnit.net 00:03:41.0190006]       Microsoft.Data.Sqlite.SqliteException : SQLite Error 5: 'database is locked'.

[xUnit.net 00:03:41.0214163]       Stack Trace:

[xUnit.net 00:03:41.0454659]         C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteException.cs(82,0): at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

[xUnit.net 00:03:42.1168601]         C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteCommand.cs(393,0): at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

[xUnit.net 00:03:42.1177707]         C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteCommand.cs(490,0): at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()

[xUnit.net 00:03:42.1183445]         C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\Extensions\SqliteConnectionExtensions.cs(16,0): at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText)

[xUnit.net 00:03:42.1189332]         C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteTransaction.cs(50,0): at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel)

[xUnit.net 00:03:42.1194367]         C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs(370,0): at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)

[xUnit.net 00:03:42.1198622]         /_/src/EFCore.Relational/Storage/RelationalConnection.cs(246,0): at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionWithNoPreconditions(IsolationLevel isolationLevel)

[xUnit.net 00:03:18.9536428]   Discovered:  Microsoft.EntityFrameworkCore.InMemory.FunctionalTests

[xUnit.net 00:03:42.1204187]         /_/src/EFCore.Relational.Specification.Tests/PropertyEntryTestBase.cs(27,0): at Microsoft.EntityFrameworkCore.PropertyEntryTestBase`1.<>c.<Property_entry_original_value_is_set>b__4_0(F1Context context)

[xUnit.net 00:03:43.8229807]         /_/src/EFCore/Extensions/ExecutionStrategyExtensions.cs(74,0): at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__2`1.<Execute>b__2_0(<>f__AnonymousType0`2 s)

[xUnit.net 00:03:43.8236119]         /_/src/EFCore/Extensions/ExecutionStrategyExtensions.cs(76,0): at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState](IExecutionStrategy strategy, TState state, Action`1 operation)

[xUnit.net 00:03:43.8241885]         /_/src/EFCore.Relational.Specification.Tests/PropertyEntryTestBase.cs(22,0): at Microsoft.EntityFrameworkCore.PropertyEntryTestBase`1.Property_entry_original_value_is_set()

[xUnit.net 00:03:43.8247654]         /_/test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs(19,0): at Microsoft.EntityFrameworkCore.PropertyEntrySqliteTest.Property_entry_original_value_is_set()

Failed   Microsoft.EntityFrameworkCore.PropertyEntrySqliteTest.Property_entry_original_value_is_set

Error Message:

 Microsoft.Data.Sqlite.SqliteException : SQLite Error 5: 'database is locked'.

Stack Trace:

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db) in C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteException.cs:line 82

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior) in C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteCommand.cs:line 393

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery() in C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteCommand.cs:line 490

   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText) in C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\Extensions\SqliteConnectionExtensions.cs:line 16

   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel) in C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteTransaction.cs:line 50

   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel) in C:\b\w\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs:line 370

   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionWithNoPreconditions(IsolationLevel isolationLevel) in /_/src/EFCore.Relational/Storage/RelationalConnection.cs:line 246

   at Microsoft.EntityFrameworkCore.PropertyEntryTestBase`1.<>c.<Property_entry_original_value_is_set>b__4_0(F1Context context) in /_/src/EFCore.Relational.Specification.Tests/PropertyEntryTestBase.cs:line 27

   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__2`1.<Execute>b__2_0(<>f__AnonymousType0`2 s) in /_/src/EFCore/Extensions/ExecutionStrategyExtensions.cs:line 74

   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState](IExecutionStrategy strategy, TState state, Action`1 operation) in /_/src/EFCore/Extensions/ExecutionStrategyExtensions.cs:line 76

   at Microsoft.EntityFrameworkCore.PropertyEntryTestBase`1.Property_entry_original_value_is_set() in /_/src/EFCore.Relational.Specification.Tests/PropertyEntryTestBase.cs:line 22

   at Microsoft.EntityFrameworkCore.PropertyEntrySqliteTest.Property_entry_original_value_is_set() in /_/test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs:line 19
```

I also seen lately occurrences of "The active test run has aborted". Are we tracking this flakiness in tests?

**Comment by bricelam** [comment]
> Are we tracking this flakiness in tests?

Andrew found a way to repro it consistently today. Tracking as aspnet/Microsoft.Data.Sqlite#408

**Comment by roji** [comment]
> Transact-SQL doesn't need them

Yikes...

**Pull request merged**
