### PR TITLE
Merge release/3.1 to master 4

### PR DESCRIPTION
**Pull request by smitpatel**
@JunTaoLuo - Should this be no-op merge to master?

### CODE REVIEW

**Comment by dougbu** [comment]
Please see https://github.com/aspnet/EntityFrameworkCore/pull/17867#issuecomment-531989959

And what is this additional branch intended for?

**Comment by smitpatel** [comment]
Trying to merge things into master, if this change should not flow to master then I can merge it as no-op merge.

**Comment by smitpatel** [comment]
Made it no-op ignoring in master.

**Comment by dougbu** [comment]
Yeah, this was right. 'master' branding remains 5.0.0-alpha1

**Pull request closed without merging**
