### PR TITLE
Explicit order (#19216)

### LINKED ISSUE #19216: Projection_of_entity_type_into_object_list is missing order
The `Projection_of_entity_type_into_object_list` is missing order, yet the `assertOrder` is set to `true`.

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #19216.

### CODE REVIEW

**Comment by smitpatel** [comment]
This broke cosmos tests. Build is broken!

**Comment by cincuranet** [comment]
It's green in ADO.
img

**Comment by roji** [comment]
Oh shoot, I'm guessing the Cosmos tests don't run on PRs? I'll take a look at this a later today (or first thing tomorrow morning, European time).

We should discuss if this is a good situation CI-wise...

**Comment by ajcvickers** [comment]
@roji I have a bit of time available now, so I'll send something out to fix the build.

> We should discuss if this is a good situation CI-wise...

We have been discussing this, and @AndriySvyryd spent considerable effort trying to get them to run reliably, with very little luck.

**Comment by AndriySvyryd** [comment]
We wouldn't run Cosmos tests on fork PRs anyway due to security concerns.

**Comment by roji** [comment]
And still no way to get the emulator onto the image somehow? How about trying to install it as part of the build itself? I know it sounds weird but it's commonly done at least in Linux CI scripts.

**Comment by roji** [comment]
Oh, and thanks for the help @ajcvickers

**Comment by smitpatel** [comment]
> We wouldn't run Cosmos tests on fork PRs anyway due to security concerns.

Does it imply that any external PR which can affect Cosmos build has to be verified locally before merging too?

**Comment by ajcvickers** [comment]
@smitpatel @AndriySvyryd @roji Let's discuss this on an internal channel.

**Pull request merged**
