### PR TITLE
Avoid deadlock in tests

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Instead throw an exception

Part of #17019

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
Seems that the underlying issue is https://github.com/dotnet/SqlClient/issues/85

**Comment by smitpatel** [comment]
I put retry for the build to see if we have consistent repro for that.

**Comment by AndriySvyryd** [comment]
I also got it locally

**Comment by AndriySvyryd** [comment]
Yup, it reproes consistently

**Comment by ajcvickers** [comment]
@AndriySvyryd I think I need a bit more details on the connection here. Can wait until I'm in the office tomorrow.

**Comment by AndriySvyryd** [comment]
@ajcvickers  See https://dev.azure.com/dnceng/public/_build/results?buildId=310306&view=ms.vss-test-web.build-test-results-tab&runId=8949696&paneView=debug&resultId=100719

**Pull request merged**
