### PR TITLE
Even more controversial: Allow creation of a DbCommand from an EF IQueryable

### PR DESCRIPTION
**Pull request by ajcvickers**
Provides access to all the real parameter values, including facets. Should be executable.

However, pretty sure people will think this isn't a good idea...

### CODE REVIEW

**Comment by roji** [comment]
This would be an alternative to #19334 rather than an addition, right?

I still find this very controversial :) A DbCommand can be seen as a tuple of SQL and parameters, which also happens to be directly executable. I like it. API-wise it's also a bit cleaner than #19334, where the parameters is an "out" parameter.

BTW it's good that this is restricted to relational - we should consider doing this regardless of whether we implement DbCommand or leave just query string.

**Comment by ajcvickers** [comment]
@roji No, this is independent of #19334 which is not relational-specific (see Cosmos) and doesn't involve handling a disposable object.

**Comment by roji** [comment]
Apologies, I meant to write above that I *don't* find this very controversial, but ended up writing the opposite.

**Comment by ajcvickers** [comment]
@AndriySvyryd @smitpatel @roji @bricelam @maumar I think we agreed in the design meeting that we were going to to this. Can I get an approval?

**Pull request merged**
