### PR TITLE
Use YAML stages

### PR DESCRIPTION
**Pull request by wtgodbe**
Resolves aspnet/AspNetCore#11924 and https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/YamlStagesPublishing.md for EFCore. @dougbu @JunTaoLuo should I port this to any of the release branches (once I have it working)?

@JohnTortugo @bricelam PTAL

Internal build is looking good as far as Stages goes: https://dev.azure.com/dnceng/internal/_build/results?buildId=300828

### CODE REVIEW

**Comment by wtgodbe** [comment]
New internal build w/ these changes rebased against rel/3.0: https://dnceng.visualstudio.com/internal/_build/results?buildId=301205

**Comment by wtgodbe** [comment]
SourceLink Validation is failing - @dougbu should I disable? @riarenas @JohnTortugo do I need to add something else like `_DotNetValidationArtifactsCategory`?

**Comment by riarenas** [comment]
@wtgodbe `_DotNetValidationArtifactsCategory` is required if you want to publish to the ".net tools -validation" channel, which is where we've been directing people to add their test builds to. It can be missing from the PR.

Sourcelink validation fails because it can't find the Azure DevOps commit in GitHub, and therefore doesn't know what to check. You can either leave it disabled for your tests, or push your latest changes to the GitHub branch. 

https://github.com/dotnet/arcade/issues/3604 tracks making this scenario better.

**Comment by dougbu** [comment]
My preference is to keep your GitHub and internal branches in sync and to test things as completely as possible. Remove checks if they're broken for better reasons 😃 

For this PR, run the following before queuing your internal build:
``` powershell
darc add-default-channel --channel ".Net Tools - Validation" --branch "refs/heads/wtgodbe:Stages2" --repo "https://github.com/aspnet/EntityFrameworkCore"
```
(ignore the documented suggestion to use https://dev.azure.com/dnceng/internal/_git/aspnet-EntityFrameworkCore because the branch also exists in GitHub)

**Comment by wtgodbe** [comment]
@dougbu would that require my internal branch to have these exact commits cherry-picked into it? The internal build I'm running is against a branch where I just copy-pasted `azure-pipelines.yml` on top of rel/3.0. I already have a channel mapping from that branch to `.Net Tools - Validation`

**Comment by dougbu** [comment]
@wtgodbe yup, the commits should match. I tend to `git push origin; git push internal` when I need internal builds for thorough testing. Just one local source to worry about.

If you're doing things using the GitHub UI, pull the branch down to your local repo then push to `internal` (assuming you have an `internal` remote for https://dnceng.visualstudio.com/internal/_git/aspnet-EntityFrameworkCore).

**Comment by wtgodbe** [comment]
New build with the dup'd commits + channel mapping: https://dnceng.visualstudio.com/internal/_build/results?buildId=301577

**Comment by wtgodbe** [comment]
Build looks good to me - @riarenas @JohnTortugo anything look amiss to you guys?

**Comment by wtgodbe** [comment]
@riarenas @JohnTortugo @dougbu @JunTaoLuo any concerns with this before I merge?

**Pull request merged**
