### PR TITLE
Merge release/3.0 to master

### PR DESCRIPTION
**Pull request by smitpatel**
`git merge release/3.0 -s ours`

### CODE REVIEW

**Comment by dougbu** [comment]
Actually, this PR isn't necessary because #16887 worked well enough. That's temporary and my comments elsewhere were about the situation _after_ dependencies start flowing in 'master' (when conflicts are far more likely). Suggest closing.

**Comment by smitpatel** [comment]
I wouldn't have to open this PR if #16887 did not add my commit to it.

**Comment by dougbu** [comment]
What do you mean @smitpatel? This PR duplicated #16887.

**Comment by smitpatel** [comment]
#16887 worked because master does not have different dependencies yet. If you wanted to ignore the dependency changes in that PR then it would be non-trivial task.
Again as @AndriySvyryd mentioned earlier, I don't know what are the dependency supposed to flow. Putting my commit in #16887 creates unnecessary overhead for me. If it did not do it, I wouldn't have to create this PR to separate my commit out.

**Pull request closed without merging**
