### PR TITLE
Oracle - Implementation of Batch Insertion

### PR DESCRIPTION
**Pull request by ralmsdeveloper**
A combination of the **6** "commits" of PR #10071
With the **updated** files from the branch **dev**!

@AndriySvyryd

### CODE REVIEW

**Comment by ralmsdeveloper** [comment]
@AndriySvyryd, if you can look, I just updated the files in a single "commit" to get a better view.
They are all updated with the dev branch files.

There is something more, I thank you and others for your patience, I want to give my best.

**Comment by anpete** [comment]
Merged, thanks!

**Comment by anpete** [comment]
@ralmsdeveloper OracleEndToEndTest.Can_save_changes started failing for us - It looks like it is not doing the batching. Any ideas?

**Comment by ralmsdeveloper** [comment]
@anpete Passed all my tests here.
```
Test started: Assembly: Microsoft.EntityFrameworkCore.Oracle.FunctionalTests.dll  
5617 passed, 0 failed, 79 skipped (see 'Error List / Messages'), took 514,91 seconds (xUnit.net 2.3.0 build 3820).
```
let me take a look!

**Comment by anpete** [comment]
Thanks! We are seeing 5 for the number of statements produced

**Comment by ralmsdeveloper** [comment]
I'm analyzing.

**Pull request merged**
