### PR TITLE
Fixed typo.

### PR DESCRIPTION
**Pull request by cincuranet**

### CODE REVIEW

**Comment by roji** [comment]
Thanks @cincuranet!

**Comment by ajcvickers** [comment]
@roji @cincuranet @maumar @smitpatel Are we sure this isn't intentional? First, it's in a call to "NormalizeDelimiters". Second, how was it working before if this is a real typo?

**Comment by ErikEJ** [comment]
Looks intentional...

**Comment by smitpatel** [comment]
Legit typo. It worked in past because Normalize replaces both open & close parenthesis to `"`

**Comment by ajcvickers** [comment]
Thanks Smit!

**Pull request merged**
