### PR TITLE
Make specification tests pass for SQLCE also 

### LINKED ISSUE #12904: {SQLCE] Specification tests fail due to SQLCE limitations
SQLCE fails to do inserts to a table with only an ID column, causing tests to fail.

Solution is to add Filler property to:
HasContextProperty
and HasContextPc
and for QueryFilterFuncletizationSqlCeTest:
PrincipalSetFilter

### Further technical details
EF Core version: 2.1
Database Provider: SQL CE
Operating system: 
IDE: VS 15.7

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #12904

### CODE REVIEW

**Comment by smitpatel** [comment]
@dotnet-bot test osx 10.12 release build

**Comment by smitpatel** [comment]
@dotnet-bot test ubuntu 16.04 release build

**Comment by smitpatel** [comment]
@ErikEJ - Can you cherry-pick the change on top of release/2.2 branch as opposed to master?

**Comment by ErikEJ** [comment]
Can you help me do that? 

Does that mean that I should base PRs on the latest release branch?

**Comment by smitpatel** [comment]
@ErikEJ - PRs are based on branch release/2.2 (for future reference). I will do the git magic to merge this PR.

**Comment by smitpatel** [comment]
Replaced by #12936

**Comment by ErikEJ** [comment]
Thanks, is that change documented anywhere? It used to be "Dev" branch

**Comment by smitpatel** [comment]
@natemcmaster - Do we have link for contributors about branching strategy?

**Comment by natemcmaster** [comment]
https://github.com/aspnet/Announcements/issues/309

**Pull request closed without merging**
