### PR TITLE
Switch to arcade model for PackageIcon

### PR DESCRIPTION
**Pull request by wtgodbe**
Merge for 3.1.1. Should fix https://github.com/aspnet/EntityFrameworkCore/issues/18749.

CC @bricelam

### CODE REVIEW

**Comment by dougbu** [comment]
'release/3.0' and 'release/3.1' use the same channel for the Arcade SDK. Why can't this be done in the lower branch?

**Comment by wtgodbe** [comment]
> 'release/3.0' and 'release/3.1' use the same channel for the Arcade SDK. Why can't this be done in the lower branch?

Because only release/3.1 has a new enough Arcade. Somebody fired off manual updates to release/3.1 a few weeks ago, but not release/3.0.

**Comment by dougbu** [comment]
If possible (again, deferring to @mmitche here), please update the Arcade SDK and target 'release/3.0'

**Comment by wtgodbe** [comment]
Closing in favor of https://github.com/aspnet/EntityFrameworkCore/pull/18909

**Pull request closed without merging**
