### PR TITLE
Correct static method call generation in CSharpHelper

### LINKED ISSUE #13985: Static method calls are generated incorrectly in code literal generation
The following type mapping literal code generation method:

```c#
public override Expression GenerateCodeLiteral(object value)
    => Expression.Call(typeof(NpgsqlNodaTimeUtils).GetMethod(nameof(NpgsqlNodaTimeUtils.InstantFromUnixTimeNanoseconds), new[] { typeof(BigInteger) }), ...);
```

Currently generates C# code calling `NodaTime.Instant.InstantFromUnixTimeNanoseconds()` - the call is on the wrong class (which should be `NpgsqlNodaTimeUtils`). The bug is here: https://github.com/aspnet/EntityFrameworkCore/blob/79bf0063bec879ba7f859e5fafbdf9a82b542a91/src/EFCore.Design/Design/Internal/CSharpHelper.cs#L767.

I'll be submitting a PR for this soon.

Originally raised in https://github.com/aspnet/EntityFrameworkCore/pull/13911#issuecomment-439844426.

### PR DESCRIPTION
**Pull request by roji**
Fixes #13985 

/cc @bricelam

### CODE REVIEW

**Comment by roji** [comment]
PS Possible candidate for patch

**Comment by ajcvickers** [comment]
#### Description

EF Core contains some code for generating simple C# literals which is used for things like scaffolding migrations. The Npgsql provider needs to generate some different literals than our other providers and this exposed a couple of bugs.
		
#### Customer Impact

Prevents people using the Npgsql provider from using NodaTime types in migrations.

#### Regression?

No.
		
#### Risk

Very low--only impacts code generation and only in specific cases. Very isolated fix.

**Comment by vivmishra** [comment]
Approved for 2.2.1

**Comment by ajcvickers** [comment]
@roji Can you re-base this patch on release/2.2? That will get it into the patch, and then we can merge release/2.2 back into master like we normally do.

**Comment by natemcmaster** [comment]
FYI I'm going to make a few changes to release/2.2 first to ensure this repo is ready to patch.

**Comment by ajcvickers** [comment]
Thanks Nate.

**Comment by natemcmaster** [comment]
https://github.com/aspnet/EntityFrameworkCore/pull/14054

**Comment by roji** [comment]
Rebased this on latest release/2.2, let me know if anything else is needed.

Do we also need a separate PR to get this into master or does some bot do that?

**Comment by bricelam** [comment]
> Do we also need a separate PR to get this into master or does some bot do that?

A bot will catch it if we forget to do it.

**Pull request merged**
