### PR TITLE
Generate symbol nupkg for EFCore.Tools, EFCore.Analyzers and dotnet-ef

### PR DESCRIPTION
**Pull request by ajaybhargavb**
Part of aspnet/Universe#1083

### CODE REVIEW

**Comment by ajaybhargavb** [comment]
@natemcmaster I can see `DotnetToolSettings.xml` is being generated inside the obj folder. How did you figure out that is what is causing the build break? I could only find an error about `VBCSCompiler.exe` not being found.

**Comment by ajcvickers** [comment]
@bricelam Can you review this and comment if the changes are things that we don't want to take for some reason?

**Comment by natemcmaster** [comment]
```
ERROR: DOTNET_TOOL_MANIFEST_MISSING: Packages with type 'DotnetTool' must have a tools manifest file named DotnetToolSettings.xml.
```
https://ci3.dot.net/job/aspnet_EntityFrameworkCore/job/release_2.1/job/linux-Configuration_Release_prtest/132/console

**Comment by ajaybhargavb** [comment]
Updated. @natemcmaster

**Comment by natemcmaster** [comment]
@ajcvickers do you want approval from @bricelam before merging?

**Comment by ajcvickers** [comment]
@bricelam If you could look at this this morning (I know you are OOF but have seen you on GitHub) that would be great.

@natemcmaster Let's give Brice a couple of hours. Is that okay?

**Comment by ajaybhargavb** [comment]
@ajcvickers https://github.com/aspnet/Universe/issues/1083 is still pending shiproom approval. So there is enough time for @bricelam to look at this.

**Pull request merged**
