### PR TITLE
Merge branch 'release/3.0' => 'master'

### PR DESCRIPTION
**Pull request by AndriySvyryd**

### CODE REVIEW

**Comment by dougbu** [comment]
@AndriySvyryd this merge PR was incorrect in that it brought dependency updates other than for Arcade across branches. It did move the versions _forward_ but only because the 5.0 naming isn't flowing well yet. So, no harm this time but please resolve merges to avoid changing non-Arcade or manually-controlled versions going forward.

**Comment by ajcvickers** [comment]
@dougbu We are routinely merging release/3.0 into master multiple times per day. If the build needs things to be different between the two branches, then it's important that you guys manage that. I don't think this is unreasonable given that we have an extra branch causing extra work for the dev team on every commit _only to make build easier_.

**Comment by dougbu** [comment]
@ajcvickers I understand the frustration with managing the additional branch. 'master' won't ready for active development for a while because the 5.0 branding changes busted various things. So, how about the following?
1. Don't bother merging the automatic PRs unless they change _more_ than dependency updates
2. Use the automatic PRs rather than doing manual merges (mixes make for nasty history 😃)
3. When resolving conflicts (which will start happening as soon as we get _some_ dependencies flowing in 'master'), preserve what's in 'master' with the possible exception of Arcade packages

FYI @JunTaoLuo and I _are_ paying attention to the merge PRs to some extent. They're just a lower priority than flowing dependencies and we're focused on flowing things in 'release/3.0-preview8' then 'release/3.0' and only then 'master'.

**Comment by smitpatel** [comment]
Just as a reference, while ignoring automatic PRs are ok but it still puts in extra step like this https://github.com/aspnet/EntityFrameworkCore/pull/16850#issuecomment-517032805
It would be useful if automatic PR generated a PR which is not just a merge PR but rather using conflict resolution strategy ignoring the changes in version file.

**Comment by dougbu** [comment]
How would a resolution strategy avoid the need to double-check the bot?

BTW I didn't mean to avoid manual merges, especially when the conflicts can't be handled in the GitHub UI. It's usually better to push to the bot's branch than to create a new PR. (Less spaghetti history.)

**Comment by smitpatel** [comment]
By using resolution strategy, you can tell git to mark a commit as merged but not take changes from it. That way when merging release/3.x branch to master, version changes from release/3.x won't flow to master. (I believe that is what we want)

**Comment by dougbu** [comment]
The problem is no specific strategy will work consistently. For example, new files that aren't relevant in 'master' will be brought in from 'release/3.0' regardless of the strategy. And point-in-time fixes from 'release/3.0-preview8' may overwrite a longer-term fix in 'release/3.0'.

**Comment by smitpatel** [comment]
Why would there be new files (or point-in-time fix) if the only change is updating dependencies?
Based on what you are saying I see there are 3 different kind of commits in release branch which need to cascade via merge.
- Purely dependency updates - This is where strategy could be useful and you can ignore the commit as each branch updates dependencies separately.
- Dev commits - Since there is no work being done in master, this are purely merge commit with all changes taken in.
- Build related commits - (the point-in-time fixes). Given it may overwrite a longer-term fix. I believe build team should do manual merge for this rather than throwing it in automatic PRs.

If 3rd is taken care of then first 2 becomes much simpler for everyone involved.

**Comment by dougbu** [comment]
> This is where strategy could be useful and you can ignore the commit as each branch updates dependencies separately.

A strategy applies to the entire merge and not specific commits. That said, I agree a merge containing only dependency update commits (without reaction changes) might merge cleanly. I don't however see the point in merging until a "real" commit is included.

> Given it may overwrite a longer-term fix. I believe build team should do manual merge for this rather than throwing it in automatic PRs.

Why create another PR when the branch of the automatic one can be corrected? In any case, the build team is going to be pretty deep underwater if we're the only people doing build-related changes. We're not solely responsible for the health of our branches.

**Comment by AndriySvyryd** [comment]
> it brought dependency updates other than for Arcade across branches.

How can I tell which dependencies are managed by Arcade?

**Comment by dougbu** [comment]
> How can I tell which dependencies are managed by Arcade?

I wasn't clear, sorry. All automatic dependency updates are managed by Arcade. But, my comment was about Arcade's own packages.

The only pertinent package in this repo is Microsoft.DotNet.Arcade.Sdk. The rest have branch-specific versioning.

**Pull request merged**
