### PR TITLE
Fix a race condition in ModelSource

### PR DESCRIPTION
**Pull request by AndriySvyryd**

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
@doug Sure, you can run the MusicStore tests with the EF package that contains this change, but I don't know how to do that.

**Comment by dougbu** [comment]
1. Build EF locally
2. Copy the relevant 3.0.0-dev package into a local folder (I use .nuget\sources in my user directory)
3. Add the folder to the NuGet.config file in the AspNetCore repo root
4. Change the Verisons.props file to use 3.0.0-dev
5. Test away. I suggest using EntityFrameworkCore\test\EF.InMemory.Test because successful runs are pretty quick.

I don't know whether you'll need to copy all EF packages into the local folder.

**Comment by dougbu** [comment]
Unless we're about to manually confirm or deny this fixes things, let's get it in.

**Comment by AndriySvyryd** [comment]
Test still hangs locally. Closing in favor of https://github.com/aspnet/EntityFrameworkCore/pull/17840

**Pull request closed without merging**
