### PR TITLE
[WIP] Install SpatiaLite on CI agents

### PR DESCRIPTION
**Pull request by bricelam**
lol, I have no idea what I'm doing... I'll just throw some YAML at it and see what happens.

### CODE REVIEW

**Comment by bricelam** [comment]
@natemcmaster @ryanbrandenburg I don't see the *Install SpatiaLite* pipeline step. Do I need to commit before it's picked up?

**Comment by natemcmaster** [comment]
This repo is not currently building on Azure DevOps due to #12842, so we disabled all PR and commit-push triggers.

**Comment by natemcmaster** [comment]
If you want to add a step to the Jenkins PR checks, you'll need to edit https://github.com/aspnet/EntityFrameworkCore/tree/release/2.2/build/buildpipeline instead. IIRC you don't need to merge those to release/2.2 to see changes.

**Comment by bricelam** [comment]
😄 Thought it was a little strange I was looking at a Jenkins UI...

**Comment by bricelam** [comment]
Closing. Will wait.

**Pull request closed without merging**
