### PR TITLE
Set 2.1 baselines

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by bricelam** [comment]
These two projects need new baselines:
* EFCore.Abstractions 
* EFCore.Proxies

**Comment by ryanbrandenburg** [comment]
Those two projects don't generate baselines because they have `<EnableApiCheck>false</EnableApiCheck>`.  What has changed that this should no longer be the case? Were they just new packages before?

**Comment by bricelam** [comment]
Just new packages in 2.1

**Comment by dougbu** [comment]
@ryanbrandenburg the type I was worried about was pseudo-internal and therefore not a concern.

Separately, looks like generating these baselines with `$(ExcludePublicInternalTypes)` set to `false` would ease reviewing this PR.

**Pull request merged**
