### PR TITLE
Adds CanConnect API for use by health checks

### LINKED ISSUE #13235: Add CanConnect or similar API for health checks
Notes:
* There will be a default relational implementation that at least opens a connection and possibly runs a query
* Relational providers can override this if something else is needed
* Non-relational providers can do whatever makes sense for them
* There will be an overload that takes something like `Func<TContext, bool>` that can be used for doing a fully custom check.

/cc @glennc @divega @rynowak

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #13235

### CODE REVIEW

**Comment by ajcvickers** [comment]
/cc @divega @glennc @rynowak 

I didn't add an overload that takes a delegate since, as Diego said previously, once the context instance has been resolved, then the health check can just execute any delegate against it directly without the need for a new method.

**Comment by ErikEJ** [comment]
Providers FYI?

**Comment by rynowak** [comment]
> I didn't add an overload that takes a delegate since, as Diego said previously, once the context instance has been resolved, then the health check can just execute any delegate against it directly without the need for a new method.

This seems fine to me.

**Comment by rynowak** [comment]
Another thing to point out and discuss. Given that this is a new API that providers need to opt in to, I was planning to document as part of the health check implementation that it will only work for providers that have implemented this interface. This means that we wouldn't put any bespoke error check in place for the case where a provider is in use that hasn't implemented the new API. So if you did this, you would see the health system report that the check failed ungracefully, and it would log the exception thrown by EF. Does that sound good enough?

**Comment by ajcvickers** [comment]
@rynowak I was envisioning it slightly differently in that if a delegate is provided, then I don't think calling CanConnect first is useful. Anything that the delegate does will likely open the connection as a first step anyway.

With regard to exceptions, I think it is reasonable that the delegate handle any exceptions that should be treated simply as "unhealthy" and return false for those. Unhandled exceptions would then be treated in the normal ungraceful place.

With regard to handling providers that don't implement this, what you suggest sounds fine. This will be rare anyway, because all relational providers inherit from the relational base class and so will get the default "Exists" implementation anyway--notice there is no special code for SQL Server or SQLite here.

**Comment by rynowak** [comment]
Good stuff, thanks!

**Comment by divega** [comment]
:+1:

**Pull request merged**
