### PR TITLE
Reduce provider dependency on internal code

### LINKED ISSUE #14923: Query: SelectExpression holds onto loggers from previous context which compiled the query
Hello,

**EF Core: master.**

I have two tests (test1 and test2), which generate equal SQL with select statement. Both tests uses one MyDbContext class.

When I run these tests one by one - no problem.

When I run these tests together (through "run all"), test2 uses RelationCommand from test1.

As I undertood it works pool of commands.

Test1 and Test2 use separate log-objects for catch a SQL of executed command.

In last case, Test2 not see execution of command, because the message passed into log1 (object from test1).

How I may resolve this problem?

I want to isolate tests from each other.

Thanks.

### PR DESCRIPTION
**Pull request by ajcvickers**
Specifically, refactoring around IRelationalCommand and its interactions so that command building can be overridden without using internals. See issue #11409.

Also, fixes #14923 by taking the logger from SelectExpressionDependencies, which is now scoped.

Made public:
* RelationalAnnotationsBuilder
* GetDeclaredForeignKeys
* GetDeclaredNavigations
* GetDeclaredProperties (Make sure also for IMutable types...)
* GetDeclaredServiceProperties
* GetDeclaredIndexes
* DisplayName (IEntityType extension)
* ShortDisplayName (System.Type extension)
* GetPropertyAccessList
* RemoveConvert
* ConfigurationSource
* CoreAnnotationNames
* GetAllBaseTypesInclusive
* Property.Format (made extension method on IEnumerable<IPropertyBase>
* FindPrincipal
* ScaffoldingAnnotationNames
* FindSharedTableRootPrimaryKeyProperty
* RelationalCommand
* RelationalCommandBuilderFactory
* RelationalCommandBuilder

Stopped using in providers:
* IndentedStringBuilder
* NonCapturingLazyInitializer

Removed:
* RelationalParameterBuilder

Also added new parameter objects as needed.

Did not touch the majority of the conventions API. Also, left most query APIs.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@roji @ErikEJ @caleblloyd 

image

Beware!

**Comment by smitpatel** [comment]
> Ideally I'd be able to build EFCore.PG against this PR to provide more feedback, but I really have no idea where I'd find the nupkgs with the right versions...

- https://dev.azure.com/dnceng/public/_build/results?buildId=127009 Download artifacts -> packages to get nupkgs
- You can also do local build of branch and reference generated artifacts directly.

**Comment by roji** [comment]
@smitpatel I can do that, but is there really no automatic publishing of packages to a nuget feed? This used to be the case with myget, did Arcade remove this?

**Comment by smitpatel** [comment]
This is PR build. They were never pushed to myget.

**Comment by roji** [comment]
My bad, I'll give the packages a try tomorrow.

**Comment by ajcvickers** [comment]
@roji Singleton to scoped could have a perf impact, but it's cleaner than before. @smitpatel and I talked briefly yesterday about this changing again for the new query pipeline. Let's see how it goes.

**Comment by roji** [comment]
@ajcvickers ok. Regardless, I'll try to sync EFCore.PG and will report any issues with public/internal.

**Pull request merged**
