### PR TITLE
Remove workaround for dotnet/arcade#1634

### PR DESCRIPTION
**Pull request by bricelam**
(Manually running on the [internal CI](https://dev.azure.com/dnceng/internal/_build/results?buildId=68596))

### CODE REVIEW

**Comment by bricelam** [comment]
Failed. Updating Arcade and trying again...

**Comment by bricelam** [comment]
Still failing. @JohnTortugo?

**Comment by JohnTortugo** [comment]
The default version of the SDK doesn't use the latest version of the SignTool ([issue is here](https://github.com/dotnet/arcade/issues/1599)) - therefore you're still using an version of SignTool that doesn't have the fix. You need to add an explicit override of the version of SignTool, e.g., adding `<MicrosoftDotNetSignToolVersion>1.0.0-beta.19057.6</MicrosoftDotNetSignToolVersion>` to eng\Version.props or adding an explicit dependency on SignTool in eng\Version.Details.xml

**Comment by bricelam** [comment]
Internal build passed. PowerShell scripts are now signed.

**Pull request merged**
