### PR TITLE
[WIP] Relax check on value generation strategy

### PR DESCRIPTION
**Pull request by ilmax**
@smitpatel this is what I was referring to in #11597, this is not ready to merge and it needs a bit more tests 😄 and few additional checks moreover it will probably be merged against master, but I wanted to bring this up to discuss the direction.

### CODE REVIEW

**Comment by roji** [comment]
Seems so...

**Comment by ilmax** [comment]
@smitpatel, @roji this is not ready to be merged as is obviously, this is more of a "Hey team, what do you think about this one?" so I opened it early to gather your feedback. I will most likely close this one or change the base branch to master

**Comment by AndriySvyryd** [comment]
This approach would work if the default strategy is Identity, but if it's SequenceHiLo then the converters would not be used.
And if you change the behavior based on the default strategy then the convention would need to re-run when the strategy is changed. This is error-prone, so I would suggest not making this change. For these scenario to work properly value generation needs to be changed more in-depth.

**Comment by ajcvickers** [comment]
@ilmax Are you still planning on moving forward with this?

**Comment by ilmax** [comment]
@ajcvickers I will start from scratch

**Pull request closed without merging**
