### PR TITLE
Migrations: Fix bug in complex column ordering code

### LINKED ISSUE #14027: `dotnet ef migrations add` produces wrong migration script
Under some specific condition, `dotnet ef migrations add` produces wrong migration script.

when

- there is two entity with same table name in context
- first entity with default schema, second entity with named schema
- second entity references first entity by ID as FK

result is
- table definition for first entity has second entity's column

My model definition (https://github.com/AtsushiSuzuki/dotnet-ef-migrations-test/blob/master/Program.cs):

```csharp
    [Table("Model")]
    public class Model1
    {
        public int Id { get; set; }
        public string Value1 { get; set; }
    }

    [Table("Model", Schema = "other")]
    public class Model2
    {
        public int Id { get; set; }
        public string Value2 { get; set; }
        public Model1 Model1 { get; set; }
    }

    public class AppContext : DbContext
    {
        public DbSet<Model2> Models { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder builder)
        {
            base.OnConfiguring(builder);

            builder.UseNpgsql("Host=localhost; Database=test; Username=postgres;");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Model2>()
                .HasOne(m => m.Model1)
                .WithMany()
                .HasForeignKey(m => m.Id);
        }
    }
```

Produced migration script (https://github.com/AtsushiSuzuki/dotnet-ef-migrations-test/blob/master/Migrations/20181128035227_Initial.cs):

```csharp
            migrationBuilder.CreateTable(
                name: "Model",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn),
                    Value1 = table.Column<string>(nullable: true),
                    Value2 = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Model", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Model",
                schema: "other",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false),
                    Value2 = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Model", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Model_Model_Id",
                        column: x => x.Id,
                        principalTable: "Model",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
```

`<default schema>.Model` erroneously have `Value2`.

### Steps to reproduce
1. clone https://github.com/AtsushiSuzuki/dotnet-ef-migrations-test
2. delete Migrations/*
3. run `dotnet ef migrations add Initial` and see results

### Further technical details
EF Core version: 2.1.4 (found in project.csproj or packages.config)
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10 Pro
IDE: VisualStudio 2017 15.9.2 (e.g. Visual Studio 2017 15.4)

### PR DESCRIPTION
**Pull request by bricelam**
I knew we'd eventually find weird corner case bugs in this code.

Fixes #14027

### CODE REVIEW

**Comment by smitpatel** [comment]
Linux failures are weird and not normal cosmos issue it seems.

**Comment by AndriySvyryd** [comment]
Also fixes https://github.com/aspnet/EntityFrameworkCore/issues/17773 ?

**Comment by bricelam** [comment]
@aspnet/efteam @aspnet/build Who broke the Linux build? Is this a known issue?
```
error NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [src/EFCore.Analyzers/EFCore.Analyzers.csproj]
error NU5128: - Add a dependency group for .NETStandard1.3 to the nuspec [src/EFCore.Analyzers/EFCore.Analyzers.csproj]
error NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [src/dotnet-ef/dotnet-ef.csproj]
error NU5128: - Add a dependency group for .NETCoreApp2.1 to the nuspec [src/dotnet-ef/dotnet-ef.csproj]
```

**Comment by smitpatel** [comment]
You hit this https://github.com/aspnet/EntityFrameworkCore/pull/18214

But it does not fail for me locally in WSL.

**Comment by dougbu** [comment]
@wtgodbe thought you said the placeholder problems resulted only in warnings? If your placeholder removal is needed here, let's get it into the 'release/3.1' branch.

**Comment by smitpatel** [comment]
@bricelam - What did you do with Linux errors? I hit the same in #18271

**Comment by bricelam** [comment]
I ignored them. They were clearly unrelated to my changes.

@wtgodbe Should we revert something while you investigate?

**Pull request merged**
