### PR TITLE
Fix Debug build break

### PR DESCRIPTION
**Pull request by ajcvickers**
See #16000

### CODE REVIEW

**Comment by ajcvickers** [comment]
@AndriySvyryd Did you test this in a build? Other tests are also failing.

**Comment by AndriySvyryd** [comment]
*Works on my machine*

**Comment by AndriySvyryd** [comment]
Seems that these failures aren't reported in VS 16.1.2 Test Explorer

**Comment by ajcvickers** [comment]
Debug.Asserts are not handled well by XUnit runners.

**Pull request merged**
