### PR TITLE
Query: Wrap up collection materialization code path for relational

### LINKED ISSUE #12098: Use single SQL query instead of split queries
I've been investigation an issue when using AutoMapper's Queryable projection extensions on top of EF Core 2.1-rc1-final. Full details including troubleshooting logs with the SQL statements are at the issue (https://github.com/AutoMapper/AutoMapper/issues/2639) and [EfAutomapperTroubleshooting.zip](https://github.com/AutoMapper/AutoMapper/files/2024473/EfAutomapperTroubleshooting.zip) is a repro. 

Basically I've got a `Booking` which has multiple `BookingItem`s. I have a DTO for each type and have configured them to be used by AutoMapper. When I execute the query on EF6 the JOIN optimization occurs (it's even smart enough that I don't need to specific the `.Include(b => b.BookingItems)`. On EF Core however, two DB queries fire (one for Booking and the other for BookingItems). Explicitly specifying the `Include` potentially would work, but it's ignored by the ["IgnoredIncludes"](https://docs.microsoft.com/en-us/ef/core/querying/related-data#ignored-includes) cleverness, so I can't force that behaviour even if I wanted to.

So there's two issues running on EF Core I'm trying to get past:
1. The JOIN optimization isn't "figured out" automatically.
2. Trying to force the JOIN with .Include(b => b.BookingItems) doesn't work either as EF Core is being clever but not clever enough. I can't see a way to turn this off or opt out per execution/context.

Obviously understanding that EF Core is not EF 6, but just wondering if this would ever be supported as it's a common scenario these days. The AutoMapper projection extensions are awesome. I'll try do this without AutoMapper for now and see if that can be my workaround for now.

### Steps to reproduce
See linked issue logged at AutoMapper and the downloadable .sln zip in my later comment.

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro, Version: 1803, OS build: 17134.48
IDE: Visual Studio 2017 15.7.1

### LINKED ISSUE #15043: QueryRewrite: re-enable tests that contain correlated subqueries

### LINKED ISSUE #15611: Query: Collection materialization code path
- Nested collections in projection
- Collection of arbitrary shape
~- Multiple collection on same level (w or w/o reference chain before)~

### PR DESCRIPTION
**Pull request by smitpatel**
Bugs fixed
- Allow ToList on collection projection to be called with less derived type
- Project out necessary identifiers for collection join when pushing down. (Except distinct case)
- Lift ordering from inner collection to generated ordered result (This would be improved further by #16226)
- Map Cast from Enumerable to Queryable
- Translate AsQueryable as no-op

Resolves #12098
Resolves #15043
Resolves #15611
Part of #15711

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
@smitpatel Are you going to merge https://github.com/aspnet/EntityFrameworkCore/pull/16327 before this?

**Comment by smitpatel** [comment]
No. Any dependencies?

**Comment by AndriySvyryd** [comment]
No, but might be conflicts

**Comment by smitpatel** [comment]
This goes first.

**Pull request merged**
