### PR TITLE
Enable YAML stages

### PR DESCRIPTION
**Pull request by wtgodbe**
Resolves https://github.com/aspnet/AspNetCore/issues/11924 and https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/YamlStagesPublishing.md for EFCore. @dougbu @JunTaoLuo should I port this to any of the release branches (once I have it working)?

@JohnTortugo @bricelam PTAL

### CODE REVIEW

**Comment by wtgodbe** [comment]
I'll spin up a private internal build w/ these changes after Tactics

**Comment by wtgodbe** [comment]
> ##[error]Metadata\Conventions\NonNullableConventionBase.cs(62,53): error CS0246: The type or namespace name 'MaybeNullAttribute' could not be found (are you missing a using directive or an assembly reference?)

Looks like one of the issues we saw in the standup yesterday @JunTaoLuo @dougbu, do we know what the fix is for this one yet?

**Comment by wtgodbe** [comment]
Internal build is looking good as far as Stages goes: https://dev.azure.com/dnceng/internal/_build/results?buildId=300828

**Comment by wtgodbe** [comment]
Closing in favor of https://github.com/aspnet/EntityFrameworkCore/pull/17040

**Comment by dougbu** [comment]
@wtgodbe don't try to make this change in 'master' as that branch is broken and our team consistently makes changes in 'release/3.0' _first_ then uses the merge bot's PRs to get things to 'master'.

**Pull request closed without merging**
