### PR TITLE
Switch to using EqualsExact in geometry comparer

### LINKED ISSUE #18921: Use exact instead of topological comparison when comparison spatial types
Our GeometryValueComparer currently compares geometry values by calling EqualsTopologically. Aside from the fact that this fails for GeometryCollection since that's unimplemented by NetTopologySuite (https://github.com/NetTopologySuite/NetTopologySuite/issues/213), it's not clear that this is the correct behavior: two geometry instances may cover the same space but be different, and for the purposes of tracking that difference seems relevant. Should we be calling EqualsExact instead?

/cc @bricelam

### PR DESCRIPTION
**Pull request by roji**
Fixes #18921

### CODE REVIEW

**Comment by bricelam** [comment]
We should review the translations for the various equals methods too

**Comment by roji** [comment]
Yeah.

Here's a useful PostGIS page on the different kind of equalities etc: https://postgis.net/workshops/postgis-intro/equality.html

Npgsql [translates](https://github.com/npgsql/efcore.pg/blob/dev/src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMethodCallTranslatorPlugin.cs#L87) EqualsExact to the PostGIS equality operator, and EqualsTopologically to [PostGIS ST_Equals](https://postgis.net/docs/ST_Equals.html). After reading the equality page above it seems like translating EqualsExact to ST_OrderingEquals may be more correct...

**Comment by roji** [comment]
Opened https://github.com/npgsql/efcore.pg/issues/1131 for the Npgsql side.

**Comment by roji** [comment]
@bricelam checked and there don't appear to be translations of EqualsExact for either SQL Server or Sqlit (SQL Server doesn't even allow equals operator: `Invalid operator for data type. Operator equals equal to, type equals geometry.`)...

Will do the translation in Npgsql (is it worth adding tests in SpatialQueryTestBase test suite if neither provider will actually exercise them...).

BTW all the tests in SpatialQueryTestBase have the tested expression in a top-level projection, which is a bit dangerous since it will do client evaluation for providers which don't translate. Any reason not to exercise them in a Where clause instead?

**Comment by bricelam** [comment]
You can add a test to the base to encourage other providers to implement it if possible.

Using Where got too tricky since precision, etc. was very different between providers. I decided asserting the SQL and loosely verifying the result was the most pragmatic thing to do.

**Pull request merged**
