### PR TITLE
Add support for VS2017

### PR DESCRIPTION
**Pull request by AndriySvyryd**

### CODE REVIEW

**Comment by bricelam** [comment]
cc @natemcmaster

**Comment by AndriySvyryd** [comment]
@bricelam flaky CI - https://github.com/aspnet/EntityFrameworkCore/pull/14418/checks?check_run_id=49901303

**Comment by ajcvickers** [comment]
@bricelam @smitpatel @AndriySvyryd Shouldn't be test ordering, since this is against Northwind and the database is not modified. However, I have seen local failures recently which lead me to believe that there may be a race condition in creating/populating Northwind.

**Comment by AndriySvyryd** [comment]
@ajcvickers Do you regularly drop Northwind locally?

**Comment by natemcmaster** [comment]
Fine as a temporary workaround, but eventually, you'll have to get onboard the VS 2019 train. Choo choo!

cref https://github.com/aspnet/AspNetCore-Internal/issues/1624

**Comment by ajcvickers** [comment]
@AndriySvyryd Not intentionally. But if I do a clean/build/test I have been seeing this quite regularly:
```
System.AggregateException : One or more errors occurred. (Cannot open database \"Northwind\" requested by the login. The login failed.\r\nLogin failed for user 'REDMOND\\avickers'.) (The following constructor parameters did not have matching fixture data: NorthwindQuerySqlServerFixture`1 fixture)\r\n---- System.Data.SqlClient.SqlException : Cannot open database \"Northwind\" requested by the login. The login failed.\r\nLogin failed for user 'REDMOND\\avickers'.\r\n---- The following constructor parameters did not have matching fixture data: NorthwindQuerySqlServerFixture`1 fixture
----- Inner Stack Trace #1 (System.Data.SqlClient.SqlException) -----
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.TestUtilities.SqlServerTestStore.OpenConnection() in C:\aspnet\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\TestUtilities\SqlServerTestStore.cs:line 245
   at Microsoft.EntityFrameworkCore.TestUtilities.RelationalTestStore.Initialize(IServiceProvider serviceProvider, Func`1 createContext, Action`1 seed) in C:\aspnet\EntityFrameworkCore\test\EFCore.Relational.Specification.Tests\TestUtilities\RelationalTestStore.cs:line 33
   at Microsoft.EntityFrameworkCore.SharedStoreFixtureBase`1..ctor() in C:\aspnet\EntityFrameworkCore\test\EFCore.Specification.Tests\SharedStoreFixtureBase.cs:line 55
   at Microsoft.EntityFrameworkCore.Query.NorthwindQueryFixtureBase`1..ctor() in C:\aspnet\EntityFrameworkCore\test\EFCore.Specification.Tests\Query\NorthwindQueryFixtureBase.cs:line 16
   at Microsoft.EntityFrameworkCore.Query.NorthwindQueryRelationalFixture`1..ctor()
   at Microsoft.EntityFrameworkCore.Query.NorthwindQuerySqlServerFixture`1..ctor()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by smitpatel** [comment]
@ajcvickers - That one seems like normal database not available right after creation issue perhaps. Do we have wait time for northwind database too? (That one has different processing here and there)

**Comment by ajcvickers** [comment]
@smitpatel Possibly. But if that is the case, then it means Northwind is being re-created even when I haven't deleted and SQL Server databases. Also, it could also be that one fixture thinks it's created and seeded when this hasn't actually completed, which would also account for the error above.

**Pull request merged**
