### PR TITLE
[2.0.2] Update Microsoft.Data.Sqlite to 2.0.1

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by natemcmaster** [comment]
@bricelam can you hold off on merging this until after we have a candidate build of 2.0.6? Universe will take care of overriding this variable to 2.0.1-rtm-XYZ when we get a first build ready

**Comment by bricelam** [comment]
Is it needed at all? EF Core 2.0.2 technically doesn't require it.

**Comment by natemcmaster** [comment]
> EF Core 2.0.2 technically doesn't require it.

Not 100% sure what you mean. But if you mean that a user could upgrade Microsoft.Data.Sqlite to 2.0.1 and leave EF at 2.0.1 or 2.0.0, then yes, *technically* we don't need EF Core to pull the update.
But even so, anytime one of our packages updates to a new patch version, we re-ship all upstream packages as well with a version bump and the upgraded dependency.

Is https://github.com/aspnet/Microsoft.Data.Sqlite/pull/475 going into the same patch release as EFCore 2.0.2?

**Comment by bricelam** [comment]
> Is aspnet/Microsoft.Data.Sqlite#475 going into the same patch release as EFCore 2.0.2?

Yes.

I'm just saying is that a local build of this branch would succeed just fine with M.D.Sqlite version 2.0.0, so if our CI will override it anyway, there's no real need to ever commit.

**Comment by natemcmaster** [comment]
> so if our CI will override it anyway, there's no real need to ever merge this.

Good point. If you don't need the updated SQlite to work on the release/2.0.0 version of EF Core for now, then let's just not merge this. After we ship releases, we go through our repos and update their deps.props to match latest stable, so this update will be done later by CI.

**Pull request closed without merging**
