### PR TITLE
Update branding to 2.2.5

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by natemcmaster** [comment]
Are we expecting to ship new EFCore packages? I wasn't aware of any EF Core 2.2.x changes for the May patch. cc @ajcvickers

**Comment by ajcvickers** [comment]
@natemcmaster We don't have anything for 2.2.x this time round.

**Comment by dougbu** [comment]
I did this mainly because we'd needed to patch 2.1 i.e. for consistency. Not a big deal either way since I wasn't planning to update the submodule in AspNetCore. LMK if I should just close this PR.

**Comment by natemcmaster** [comment]
Let's close this to avoid future confusion about whether or not there should have been a 2.2.5 EFCore package.

**Pull request closed without merging**
