### PR TITLE
Update SqlServerDatabaseModelFactory.cs

### PR DESCRIPTION
**Pull request by yzi2004**

### CODE REVIEW

**Comment by smitpatel** [comment]
@yzi2004 - Can you explain why this change is required? It has no functional impact. T-SQL can use implicit column alias name from projection in order by.

**Comment by yzi2004** [comment]
@smitpatel  I have  some sql server 2008 R2 database, But for some reason, it is running in compatibility level 80. When I is scaffold db, I get a error [Msg 209, Level 16, State 1, Line 1 Ambiguous column name 'name'.].

**Comment by smitpatel** [comment]
@yzi2004 - EF Core supports SqlServer 2008 and above only. i.e. Databases which has compatibility level at least 100. So connecting to database with compat level 90 on SqlServer 2014 instance wouldn't work.
While this change would make scaffolding Db scenario work, the EF Core will still fail at runtime because the SQL we generate from runtime may not adhere to what is supported on older version of SqlServer.
Are you planning to use the same database with EF? Or you are just trying to use scaffolding tool? Can you give us more details on how you plan to use EF Core with your database?

**Comment by yzi2004** [comment]
@smitpatel  **EF Core supports SqlServer 2008 and above only.**  I see.   We have a asp.net mvc site access this database by EF 6.2 , I just want to convert it to asp.net core for study.

**Pull request merged**
