### PR TITLE
Add a dependency on Analyzers to each package

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by divega** [comment]
@bricelam curious, why do we need to do this? Feels like something is broken.

**Comment by bricelam** [comment]
NuGet doesn't propagate analyzers by default. This lets the dependency flow from Microsoft.EntityFrameworkCore through all of our packages and into the user's project.

Without this, the user's project would have to reference Microsoft.EntityFrameworkCore directly in order to get the analyzer.

**Comment by bricelam** [comment]
N.B. The title doesn't reflect the actual implementation. 😉

**Comment by anpete** [comment]
cc @roji @ErikEJ @cincuranet @ralmsdeveloper @caleblloyd At the moment it looks like providers need to add the analyzer dependency so that the analyzer will show up for users that only reference the provider.

**Comment by roji** [comment]
@anpete are you saying providers should reference `Microsoft.EntityFrameworkCore.Analyzers`? Because this PR doesn't do that for SqlServer/Sqlite...

**Comment by anpete** [comment]
cc @bricelam for @roji's question - I think we need to do that

**Comment by bricelam** [comment]
Hmm, the best thing for providers is probably to use `PrivateAssets="none"`:
``` xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational"
                  Version="2.1.0-*"
                  PrivateAssets="none" />
```
This will allow us to propagate analyzers and any additional assets in the future.

**Comment by bricelam** [comment]
See [Controlling dependency assets](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets) in the NuGet docs for exactly what `PrivateAssets` means.

**Comment by bricelam** [comment]
Note, if your project needs to be compatible with older versions of MSBuild/VS, write it like this:
``` xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational">
  <Version>2.1.0-*</Version>
  <PrivateAssets>none</PrivateAssets>
</PackageReference>
```

**Comment by ErikEJ** [comment]
And if I use a Nuspec? 🤔

**Comment by bricelam** [comment]
@ErikEJ just make sure your `<dependency>` ***doesn't*** list `Analyzers` in the `exclude` attribute. If you want to be explicit, you can add `include="all"`.
``` xml
<!-- DON'T DO THIS -->
<dependency id="Microsoft.EntityFrameworkCore.Relational"
            version="2.1.0-preview1-final"
            exclude="analyzers" />

<!-- Optionally do this -->
<dependency id="Microsoft.EntityFrameworkCore.Relational"
            version="2.1.0-preview1-final"
            include="all" />
```

**Comment by roji** [comment]
Done in Npgsql

**Pull request merged**
