### PR TITLE
Change Private Methods to Protected Virtual in DbContext and EntityType Generators

### PR DESCRIPTION
**Pull request by tonysneed**
Open up extensibility points in the DbContext and EntityType generators to allow for scaffolding customization. 

**Please check if the PR fulfills these requirements**

- [x] The code builds and tests pass (verified by our automated build checks)
- [x] Commit messages follow this format
```
    Summary of the changes
    - Detail 1
    - Detail 2

    Fixes #bugnumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Code meets the expectations our engineering guidelines. https://github.com/aspnet/Home/wiki/Engineering-guidelines.

Please review the guidelines for CONTRIBUTING.md for more details.

### CODE REVIEW

**Comment by smitpatel** [comment]
@tonysneed - Please run build locally using `.\build.cmd` script. It has failures. Also don't move methods around. It makes it harder to diff.

**Comment by tonysneed** [comment]
I see it .. failing test .. will fix.

**Comment by tonysneed** [comment]
@smitpatel I put the methods back where they were so the diffs should be easier to read now. 😄

**Comment by smitpatel** [comment]
Merged via f44eaa4bbd80e0223cf5888d67627405f14629eb

@tonysneed - Thank you for contribution.

**Pull request closed without merging**
