### PR TITLE
Ensure that ILoggerFactory is re-captured for each context Instance

### PR DESCRIPTION
**Pull request by ajcvickers**
Otherwise the wrong (possibly disposed) logger factory can be used.

Fixes part of ASP.NET build break.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@bricelam @smitpatel @AndriySvyryd @roji This is to fix a break in ASP.NET, which could also impact real applications, so an expedient review would be appreciated.
/cc @dougbu @natemcmaster

**Comment by AndriySvyryd** [comment]
Shouldn't it also be reset for pooled contexts?

**Comment by ajcvickers** [comment]
@AndriySvyryd Interesting. I'll go check.

**Comment by ajcvickers** [comment]
Going to merge this now and then look at pooling.

**Pull request merged**
