### PR TITLE
Improve logging of datetime DbParameter values

### LINKED ISSUE #8150: New specification test fails with SQLCE provider
@smitpatel 

Running this new test:
https://github.com/aspnet/EntityFramework/blob/0748e3e8b942855db7035d6a8dff98a8cb77584c/src/EFCore.Specification.Tests/QueryTestBase.cs#L3353

(Just noticed it also fails on my PC with the SQLite and SQL Server test)

```
Expected: Object[] [{ cust = Customer RATTC, ords = 18 }, { cust = Customer OLDWO, ords = 10 }, { cust = Customer GALED, ords = 5 }, { cust = Customer LILAS, ords = 14 }, { cust = Customer MAGAA, ords = 10 }]
Actual:   Object[] [{ cust = Customer DRACD, ords = 6 }, { cust = Customer RATTC, ords = 18 }, { cust = Customer OLDWO, ords = 10 }, { cust = Customer GALED, ords = 5 }, { cust = Customer LILAS, ords = 14 }]
	at Microsoft.EntityFrameworkCore.Specification.Tests.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Boolean assertOrder, Action`2 asserter)
	at Microsoft.EntityFrameworkCore.Specification.Tests.QueryTestBase`1.AssertQuery[TItem1,TItem2](Func`3 efQuery, Func`3 l2oQuery, Boolean assertOrder, Nullable`1 entryCount, Action`2 asserter)
	at Microsoft.EntityFrameworkCore.Specification.Tests.QueryTestBase`1.AssertQuery[TItem1,TItem2](Func`3 query, Boolean assertOrder, Nullable`1 entryCount, Action`2 asserter)
	at Microsoft.EntityFrameworkCore.Specification.Tests.QueryTestBase`1.GroupJoin_customers_orders_count_preserves_ordering()
```

### Further technical details
EF Core version: 2.0.0-preview1-24394
Database Provider: EntityFrameworkCore.SqlServerCompact40
Operating system: Win 10
IDE: (e.g. Visual Studio 2015)

### LINKED ISSUE #9319: Improve logging of datetime parameter values
Current way hurts my European eyes, and prevents safe reuse of logged SQL for debugging etc.

Current: 01/02/2019 14:11:12 (DateTime.ToString() with InvariantCulture)

Proposed: Datetime.ToString("s")/DateTimeOffsset.ToString("o")

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #9319

### CODE REVIEW

**Comment by smitpatel** [comment]
@ErikEJ - Test failures in SqlServer Functional tests (check appveyor). You would need to update SQL Assertion where such parameters are being passed. Thanks.

**Comment by ErikEJ** [comment]
@smitpatel Missed that they did not run on my PC - it got this error, that I do not understand:

__exec : dotnet.exe failed with exit code: 1
At C:\Users\ErikEjlskovJensen\.dotnet\buildtools\korebuild\2.1.0-preview1-15479\scripts\KoreBuild.psm1:104 char:9
+  __exec $global:dotnet msbuild `@"$msBuildResponseFile"
+  < ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,__exec

**Comment by smitpatel** [comment]
@natemcmaster for korebuild error.
@ErikEJ - Try doing git clean -xdf and run build again.

**Comment by smitpatel** [comment]
Also this does not fix #8150

**Pull request closed without merging**
