### PR TITLE
Prevent dependents from being deleted when principal is deleted

### LINKED ISSUE #12590: Handle entity replacement in TrackGraph with better exception/message
I'm writing integration tests using the In-Memory provider, and I ran into something that is causing me to scratch my head.

I have some code like this:

```c#
_dbContext.ChangeTracker.TrackGraph(
	entity, n => {
		n.Entry.State = entity.IsNew ? EntityState.Added : EntityState.Modified;
	});
```

This works with object graphs when going against SQL server, and each object in the graph get's its EntityState set. But when I run through it with entities fetched using the in-memory provider, it doesn't seem to traverse the graph, and only updates the base entity.

Am I doing something wrong? Or is this the expected behavior?

Thanks

### Further technical details
EF Core version: 2.1.1.0
Database Provider: In-Memory
Operating system: 
IDE: Visual Studio 2017 15.8.0 Preview 3.0

### LINKED ISSUE #18982: Detaching an entity results in related entities being deleted
EF Core 3.0.1

I insert an object along with related objects. Then I set the state of the object to "Detached". I then perform another call to `.SaveChangesAsync()`.

Observed behavior: the related objects are deleted.
Expected behavior: the related objects should not be deleted; rather their tracking status should simply be set to "Detached".

(This is a breaking change since upgrading from EF Core 2.2.4)

### Steps to reproduce

```
    public class Thing
    {
        [Key]
        public Guid ThingId { get; set; }
        [MaxLength(200)]
        public string Description { get; set; }
        public List<OwnedByThing> OwnedByThings { get; set; } = new List<OwnedByThing>();
    }

    public class OwnedByThing
    {
        [Key]
        public Guid OwnedByThingId { get; set; }
        public Guid ThingId { get; set; }
        public Thing Thing { get; set; }
        public int Value { get; set; }
    }

            await using var db = new MyDbContext();
            var thing = new Thing
            {
                Description = "Hello world thing",
                OwnedByThings = new List<OwnedByThing>
                {
                    new OwnedByThing {Value = 1},
                    new OwnedByThing {Value = 2}
                }
            };

            db.Things.Add(thing);
            await db.SaveChangesAsync();

            var thingCount = await db.Things.CountAsync(e => e.ThingId == thing.ThingId);
            Assert.AreEqual(1, thingCount, "Thing Count A");
            var ownedCount = await db.OwnedByThings.CountAsync(e => e.ThingId == thing.ThingId);
            Assert.AreEqual(2, ownedCount, "Owned count A");

            db.Entry(thing).State = EntityState.Detached;
            await db.SaveChangesAsync();
            
            thingCount = await db.Things.CountAsync(e => e.ThingId == thing.ThingId);
            Assert.AreEqual(1, thingCount, "Thing Count B");
            ownedCount = await db.OwnedByThings.CountAsync(e => e.ThingId == thing.ThingId);
            Assert.AreEqual(2, ownedCount, "Owned count B");
```
Result:
``` 
  Owned count B
  Expected: 2
  But was:  0
```

### Further technical details

EF Core version: 3.0.1
Database provider: Npgsql
Target framework:.NET Core 3.0
Operating system: Windows 10 Pro
IDE: JetBrains Rider

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #12590
Fixes #18982
Regression test for #16546

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
I think you meant "Prevent dependents from being deleted when principal is **detached**"

**Comment by shaulbehr** [comment]
Thanks for fixing! What release will this be in?

**Comment by ErikEJ** [comment]
5.0 !

**Comment by silvajpr** [comment]
Not acceptable to be release only on version 5!
By the way for me the Expected behavior is the related objects should KEEP / REMAIN the actual state - it shouldn’t be affected - it’s the beahvior of EF6 and EFCore 2.2.
Exemple: if the related object state is Added it should continue with that state!
For me doesn’t make sense to also detach the related objects.
Take this example: the principal exist in the DB and I simply want to remove it from the tracking changes, without any side effects in the related objects! (Maybe I have change some value and I don’t want it to be saved or another reason).
How can I do what I just explained?
Thanks

**Pull request merged**
