### PR TITLE
Implement reverse engineering of views for SQLite

### LINKED ISSUE #1679: RevEng: Support Views
Note: This issue is tracking a specific aspect of using EF Core with database views. See #827 for an overview of the areas where EF Core interacts with database views. The completion of this feature does not mean that every aspect of database view support has been implemented.

---
See also #5719, which is about support for tables without keys.

Part of #830. At the moment we generate code only from tables, not views. Need to include views but may have to consider what we want to use as the primary key.

### PR DESCRIPTION
**Pull request by ErikEJ**
Part of #1679

### CODE REVIEW

**Comment by smitpatel** [comment]
@ErikEJ - We also need to update code to scaffold EntityType class for these DatabaseModels & appropriate code in OnModelCreating. The feature is not done till then. At present it would generate DatabaseModel but then generate warning that could not scaffold entityType for it.

**Comment by ErikEJ** [comment]
Ok, I thought this was already done.

**Comment by ErikEJ** [comment]
@smitpatel Where does the scaffolding code gen reside? Looking in vain.

**Comment by smitpatel** [comment]
@ErikEJ - RelationalScaffoldingModelFactory at present blocks the EntityTypes to be generated when there are no PK. Check `RelationalScaffoldingModelFactory.VisitTable` method.

After it pass-through that as keyless entityType, you would need to modify `CSharpDbContextGenerator.GenerateEntityType` code to skip key if not present and rather generate HasNoKey() API.

**Comment by ErikEJ** [comment]
@smitpatel Can this be merged?

**Comment by smitpatel** [comment]
@ErikEJ - Sorry, forgot to merge this earlier.

**Comment by ErikEJ** [comment]
Thanks!

**Pull request merged**
