### PR TITLE
[2.0.2] Tools: Force runtime configuration file generation

### LINKED ISSUE #10298: Problem with dotnet cli ef tools after upgrading to vs 2017 15.4.4 and november .net core rollup
Not sure if its an EFCore issue or cli

#  Steps to reproduce
Using Visual Studio Enterprise 2017 (v 15.4.4)
# Add migration
dotnet ef migrations add [MigrationName]
# Expected behavior
Migration created

# Actual behavior
Error message :
The specified framework version '2.0' could not be parsed
The specified framework 'Microsoft.NETCore.App', version '2.0' was not found.
Check application dependencies and target a framework version installed at:
\\
Alternatively, install the framework version '2.0'.

My project is a console library and the content of .csproj file is below:
``` csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Reflection.Metadata" Version="1.5.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
  </ItemGroup>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
</Project>
```

So i tried to use global.json in the root of my project  : 
```
{
  "sdk": {
    "version": "2.0.3"
  }
}

```

and the error was the same.
But when I changed global.json content to this :

```
{
  "sdk": {
    "version": "2.0.2"
  }
}

```
It worked.

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #10298 

Verification: Manually tested

### CODE REVIEW

**Comment by bricelam** [comment]
Now we just need a branch to put this in...

**Comment by ajcvickers** [comment]
@bricelam Let's assume it's going to go into a 2.0.2 branch in the normal way. Can you set that up, or do we need to sync on infra issues?
/cc @Eilon @natemcmaster

**Comment by Eilon** [comment]
@natemcmaster would know the right "temporary" branch name until we start the actual patch cycle.

**Comment by natemcmaster** [comment]
If you can hold off for a few days, I can get you some instructions on branching, tags, etc. I'm working on simplifying and cleaning up our 2.0.x build system so it works better with the Orchestrated Build plan. Should have instructions later this week or early next week.

**Comment by bricelam** [comment]
Happy to wait.

**Comment by natemcmaster** [comment]
For 2.0.x patches, here is what you should do:

- Merge all 2.0.x patch changes to the `release/2.0.0` branch.
- Increment the VersionPrefix in version.props by one patch version. 
- Update the `release/2.0.0` branch of aspnet/Universe. (I'll take care of this - we're not quite ready to start the next 2.0.x patch).

**Pull request merged**
