### PR TITLE
DATEDIFF implementation for Oracle

### PR DESCRIPTION
**Pull request by ralmsdeveloper**
**Implementing DATEDIFF for Oracle**

- YEAR
- MONTH
- DAY
- HOUR
- MINUTE
- SECOND

### CODE REVIEW

**Comment by ralmsdeveloper** [comment]
As the test server is giving errors, here are my tests, everything is satisfactory!

------ Test started: Assembly: Microsoft.EntityFrameworkCore.Oracle.FunctionalTests.dll ------
6140 passed, 0 failed, 51 skipped (see 'Error List / Messages'), took 475,52 seconds (xUnit.net 2.3.1 build 3858)

/cc @bricelam @smitpatel

**Comment by smitpatel** [comment]
@ralmsdeveloper - We have decided not to add DateDiff based function for other providers since that function is basically a T-SQL function and customers using other providers may find very little value in it. Certainly based on client side representation, we can arrive at some translation on server side but it would probably un-natural for customer to use such methods. That is the reason we removed translation from SQLite provider also.

Ideally, what we want to translate is date subtraction to server. Currently which has its own mapping issue. i.e. Date subtraction returns TimeSpan but SqlServer has no mapping for that type, so by some means if we arrive at computation of TimeSpan we still cannot create the object on client side properly. But that is SqlServer (and also Sqlite) limitation. Postgre perfectly maps TimeSpan to interval type on database. So if Oracle has a type which would map well with TimeSpan in C# then we would perhaps map it and translate date subtraction as is (or with function) to return TimeSpan.

If Oracle does not have a mapping type then we can look at some well-known Oracle Sql functions which customers find useful and add them to EF.Functions (same as SqlServer adds DateDiff based methods). You can file a new issue for that to start discussion on that.

Hope this explains what direction we are taking when it comes to extending EF.Functions to add provider specific functions. If you have any questions feel free to ask.

With all above in mind, we are not adding DateDiff functions for Oracle so I am closing this PR. (hence I haven't added any feedback)

**Comment by ralmsdeveloper** [comment]
@smitpatel thanks for every explanation!

But you simply can not handle Oracle by comparing with Postgre.
Another thing is TimeSpan is totally limited. 
In a case of retrieving seconds, hours, minutes ... there would have to be an extension anyway!
And yes, Oracle also does the mapping, but I believe it will be difficult to try to do this kind of translation because you have TimeSpan limited to just some information.

Anyway thank you very much for the explanation, I would like to know if you have any idea to translate (Hour, Minute, Second) with TimeSpan.

Long time ago I did an extension for this, but you said it was not what you wanted!

**Comment by smitpatel** [comment]
We precisely do not want DateDiff functions on other providers if the provider SQL does not have DateDiff. The boundary definition is bit hard to be put to use for general case and it is less likely that folks not using SqlServer would want to use that. If you have any ideas, create an issue, we can discuss in detail.

**Comment by ralmsdeveloper** [comment]
@smitpatel yes I will create a problem, there are many situations to use.

**Pull request closed without merging**
