### PR TITLE
[3.1.1] Query: Don't use VisitAndConvert in projectionBindingExpressionVisitor

### LINKED ISSUE #18888: Projection with parameterized constructor fails
The following code worked fine with EF Core 2.2, but no longer with EF Core 3:

``` C#
        var wrappedEntities = context.Products
          .Select(p => new ProductWrapper(p));
```

The exception text reads: 

> System.InvalidOperationException: 'When called from 'VisitMemberInit', rewriting a node of type 'System.Linq.Expressions.NewExpression' must return a non-null value of the same type. Alternatively, override 'VisitMemberInit' and change it to not visit children of this type.'

Using a parameterless constructor and passing the entity via a public property works:

``` C#
        var wrappedEntities = context.Products
          .Select(p => new ProductWrapper
          {
            Entity = p
          });
```

Is this a bug or an intended breaking change: [Linq queries are no longer evaluated on the client](https://docs.microsoft.com/de-de/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client)

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.3.9

### PR DESCRIPTION
**Pull request by smitpatel**
Since visiting inner could return null

Resolves #18888

### CODE REVIEW

**Comment by ajcvickers** [comment]
Removing `servicing consider` this morning since we don't have the template done yet.

**Comment by smitpatel** [comment]
Description
In new query pipeline, we were using `ExpressionVisitor.VisitAndConvert` function in certain places. The function throws exception if Visit returned null expression. In 2 specific visitor we return null if we fail to translate something to SQL so that we can throw better exception or client eval the projection. But usage of `VisitAndConvert` ended up throwing early and useless exception message.

Customer Impact
Query failure when query involves DTO construction with parameter in projection.

How found
Customer-reported (#18888)

Test coverage
We did not have test coverage where DTO took parameter in ctor.

Regression?
Yes, from 2.2.

Risk
Small. Instead of using `VisitAndConvert`, we call `Visit` only and not throw any exception if null returned. It is same as underlying code of `VisitAndConvert` except exception throwing mechanism.

**Comment by smitpatel** [comment]
@ajcvickers - filled it.

**Comment by ajcvickers** [comment]
@smitpatel This is approved for **3.1.1** servicing. Please merge ASAP.

**Comment by jamshedd** [comment]
Approved for 3.1.1

**Pull request merged**
