### PR TITLE
Query: Support ICollection<T>.Contains

### PR DESCRIPTION
**Pull request by smitpatel**
Additional PR to clean up #17469
Also re-targeted to release/3.1

### CODE REVIEW

**Comment by wdnijdam** [comment]
This change does not work for Support IReadOnlyCollection<T>.Contains()

IReadOnlyCollection is translated correctly by EF core 2.2. It would make more sense to translate IReadOnlyCollection since it covers ICollection and Array as well.

**Comment by smitpatel** [comment]
@wdnijdam - Your issue is unrelated to this.

**Comment by gojanpaolo** [comment]
Hello, is there an issue for having the following query translated by ef core? 

```c#
var words = new[] { "foo", "bar" };
ctx.Post.Where(p => words.Any(p.Title.Contains));
```

This is the closest related issue I could find, but I'm pretty sure there is already an issue for this, I just don't know the terms to search for. Thanks!

**Comment by wdnijdam** [comment]
The problem occurs when the local variable "words" is modified into a readonly field.
________________________________
Van: Jan Paolo Go <notifications@github.com>
Verzonden: maandag 30 maart 2020 22:20
Aan: dotnet/efcore <efcore@noreply.github.com>
CC: Nijdam, Willem-Derk <willem-derk.nijdam@t-mobile.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [dotnet/efcore] Query: Support ICollection<T>.Contains (#17599)


Hello, is there an issue for having the following query translated by ef core?

var words = new[] { "foo", "bar" };
ctx.Post.Where(p => words.Any(p.Title.Contains));

This is the closest related issue I could find, but I'm pretty sure there is already an issue for this, I just don't know the terms to search for. Thanks!

**Pull request merged**
