### PR TITLE
Added support for unique constraints.

### PR DESCRIPTION
**Pull request by ghost**
Candidate keys in the core model become unique constraints in the relational model.

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
Could you please elaborate how to use it without configuring the dbcontext via model? Is it so that we can use it in model as follow:

```c#
[Unique]
public int SomeSurrogateKey { get; set; }
```

If such an attribute is available now, please consider putting it in some news highlight blog/article, because as far as I can tell, this feature (marking property as key using C# decorator in model) has high demand in ASP.NET MVC dev community.

Thanks in advance.

**Comment by bricelam** [comment]
@jasonwilliams200OK Data annotations aren't supported yet. (See #107) Currently, there is no way to define an alternate (non-primary) key using `ModelBuilder` except by specifying a foreign key that references it:

```C#
modelBuilder.Entity<CreditReport>()
    .Reference(r => r.Person).InverseCollection()
    .ForeignKey(r => r.PersonSSN).PrincipalKey(p => p.SSN);
```

You can also "drop down" to core metadata:

```C#
var model = modelBuilder.Model;
var person = model.GetEntityType(typeof(Person));
var ssn = person.GetProperty("SSN");
person.AddKey(ssn);
```

**Comment by julielerman** [comment]
I sure prefer the 2nd way! No dependency on an FK or navigation property. Is the first example showing something people want to do with unique constraints in a database?

**Comment by bricelam** [comment]
@jasonwilliams200OK @julielerman I'm moving the conversation to #2164 since there seems to be a usability issue here.

**Comment by julielerman** [comment]
*like* :)

**Comment by ajcvickers** [comment]
@julielerman What is your goal in having the unique constraint? The reason I ask is that if you do it the second way, then it means nothing to the EF runtime. EF will not behave any differently at all. The only thing that will happen is that if, and only if, the database is created using Migrations, then the constraint will be added in the database, but this still will not change EF behavior at all.

**Comment by julielerman** [comment]
I personally don't have a particular goal outside of knowing people have requested the feature, you've implemented it and I want to see how it works and let folks know about it. :) Yeah the second way only affects the database. I get that. The first will allow EF to also attend to the constraints. I am just always wary of the dependence on navigation properties since I put a lot of focus on DDD patterns.

**Pull request closed without merging**
