### PR TITLE
Replace solutions with solution filters

### PR DESCRIPTION
**Pull request by AndriySvyryd**

### CODE REVIEW

**Comment by roji** [comment]
While this is very cool, it doesn't yet seem to be supported by Resharper/Rider... Can we please hold off on this for now?

**Comment by AndriySvyryd** [comment]
@roji @ajcvickers Let me know when it works

**Comment by roji** [comment]
https://youtrack.jetbrains.com/issue/RIDER-27139

**Comment by roji** [comment]
@AndriySvyryd Resharper/Rider 2019.2 is now out and supports this - unblocked.

**Pull request merged**
