### PR TITLE
Include EFCore.Design in EFCore.Runtime.sln

### PR DESCRIPTION
**Pull request by bricelam**
It's important to include this project when refactoring runtime code.

And hey, even I don't like to see all those tools packages sometimes. 😉

### CODE REVIEW

**Comment by bricelam** [comment]
Metadata was my main concern. We changed the behavior of `Relational().StoreType` and needed to react in Design.

**Comment by bricelam** [comment]
A lot of new features also require implementation in Design. Design uses Internal APIs too so you may break it without realizing it...

**Comment by bricelam** [comment]
Do we need an EFCore.Query.sln?

**Comment by bricelam** [comment]
Tools on the other hand are very isolated and only need to be changed when additional new features to them.

**Comment by smitpatel** [comment]
Let's discuss in triage today. EFCore.Query.sln is also fine :)

**Pull request merged**
