### PR TITLE
Explicit culture in tests

### LINKED ISSUE #14847: Microsoft.EntityFrameworkCore.Relational.Specification.Tests should explicitly set CultureInfo
The `Microsoft.EntityFrameworkCore.Relational.Specification.Tests` package should explicitly set `CultureInfo` for the test(s), else comparison is different and some (in my case query) tests fail (in my case on ordering).

### Further technical details
`Microsoft.EntityFrameworkCore.Relational.Specification.Tests`: 2.2.0

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #14847.

### CODE REVIEW

**Comment by roji** [comment]
I wonder if it's not better to put this kind of thing in an assembly-level initialization - putting it in RelationalTestStoreFactory means it doesn't happen for non-relational stores (e.g. Cosmos) or in regular (non-functional) tests. A slight downside is that this would have to be done for every assembly, including external providers - but that seem to make sense.

xunit doesn't have anything specific for this (see https://github.com/xunit/xunit/issues/431), but there's a [code sample](https://github.com/xunit/samples.xunit/tree/master/AssemblyFixtureExample) that shows how it can be done.

**Comment by cincuranet** [comment]
The best option would be to use explicit cultures/comparisons for the locally executed parts of the query. Then we don't have to fiddle with this. But that would take some time.

Assembly level would be good as well, but for me personally the sample from xUnit is more like a workaround than a solution, especially given the tests are shared (and given it would have to be done in every assembly).

Maybe good enough option is placing it to `FixtureBase`

**Comment by ajcvickers** [comment]
@cincuranet Curious: how many tests are failing due to culture issues and what does a typical failure look like?

**Comment by cincuranet** [comment]
I think that highly depends on the locale itself and how much it diverges in comparison/sorting from the En or invariant.

I can run with Czech on Monday and let you know (I fixed the first failing test once I realized it's this, so I don't know the total).

**Comment by cincuranet** [comment]
With Czech locale, which is very close to English or invariant, 12 tests fail.

**Comment by roji** [comment]
@cincuranet thanks for the info, that could actually mean the test or even the product itself has an issue... We discussed briefly in triage, and the advantage of *not* setting invariant culture globally is precisely to uncover this kind of issue.

Do you feel like taking a look at the failing tests?

**Comment by cincuranet** [comment]
I'm afraid I don't have much free time to investigate at the moment.

**Comment by roji** [comment]
In that case can you please open a new issue with the names of the failing tests? We can keep this open to continue discussing the idea of globally setting the invariant culture.

**Comment by cincuranet** [comment]
Done in #14912.

**Comment by ajcvickers** [comment]
@roji @smitpatel I think we decided in triage to not set the culture globally. Is this also your memory? If so, we should close this PR.

**Comment by roji** [comment]
Right, the idea was not to set the culture globally in order to catch places where we don't handle culture correctly in the product. We already have a list of such failing tests in #14912, am closing this.

**Pull request closed without merging**
